import { createAdminClient } from "@/lib/supabase/admin";
import { computeLeagueStats } from "@/lib/league-stats";

export const dynamic="force-dynamic";
type Pred={gameweek_id:string;member_id:string;fixture_id:string;points_awarded:number|null};
type Fixture={id:string;competition:string;country:string;odds_fractional:string|null};
type Adjustment={gameweek_id:string;member_id:string;points:number;reason:string};

function movement(value:number){return value>0?`↑ ${value}`:value<0?`↓ ${Math.abs(value)}`:"—"}

export default async function PublicStatsPage(){
 const admin=createAdminClient();
 const [{data:season},{data:profiles},{data:settings}]=await Promise.all([
  admin.from("seasons").select("id,label").eq("is_current",true).maybeSingle(),
  admin.from("profiles").select("id,display_name").eq("approved",true).eq("active",true),
  admin.from("league_settings").select("current_season_label").eq("id",true).maybeSingle()
 ]);
 const {data:gameweeks}=season?.id?await admin.from("gameweeks").select("id,number").eq("season_id",season.id).order("number"):{data:[]};
 const ids=(gameweeks??[]).map(g=>g.id);let predictions:Pred[]=[];let adjustments:Adjustment[]=[];
 if(ids.length){const [p,a]=await Promise.all([admin.from("predictions").select("gameweek_id,member_id,fixture_id,points_awarded").in("gameweek_id",ids),admin.from("score_adjustments").select("gameweek_id,member_id,points,reason").in("gameweek_id",ids)]);predictions=(p.data??[]) as Pred[];adjustments=(a.data??[]) as Adjustment[];}
 const fixtureIds=[...new Set(predictions.map(p=>p.fixture_id))];let fixtures:Fixture[]=[];if(fixtureIds.length){const f=await admin.from("fixtures").select("id,competition,country,odds_fractional").in("id",fixtureIds);fixtures=(f.data??[]) as Fixture[];}
 const latestScored=(gameweeks??[]).filter(g=>predictions.some(p=>p.gameweek_id===g.id&&p.points_awarded!=null)||adjustments.some(a=>a.gameweek_id===g.id)).at(-1)?.number??(gameweeks??[]).at(-1)?.number??0;
 const stats=computeLeagueStats({profiles:(profiles??[]).map(p=>({id:p.id,name:p.display_name})),gameweeks:gameweeks??[],predictions,adjustments,fixtures,cutoffNumber:latestScored});
 const {rows,headlines,recap}=stats;const seasonLabel=season?.label??settings?.current_season_label??"2026/27";
 return <main className="spectatorPage"><header className="spectatorHero"><div className="spectatorHeroCopy"><span>SEASON {seasonLabel} · LEAGUE STATS</span><h1>BOUNCE</h1><h2>SEASON STORY</h2><p>Form, strike rate, streaks and the numbers behind every pick.</p></div></header><nav className="spectatorNav"><a href="/table">Live League</a><a className="active" href="/stats">League Stats</a><a href="/login">Member Login</a></nav>
 <section className="publicStatsLeaders"><article><span>LEAGUE LEADER</span><strong>{headlines.leader?.name??"—"}</strong><small>{headlines.leader?`${headlines.leader.points} pts`:"No scores"}</small></article><article><span>BEST FORM</span><strong>{headlines.bestForm?.currentStreak?headlines.bestForm.name:"—"}</strong><small>{headlines.bestForm?.currentStreak?`${headlines.bestForm.currentStreak} straight +3s`:"No active streak"}</small></article><article><span>STRIKE RATE</span><strong>{headlines.bestStrike?.name??"—"}</strong><small>{headlines.bestStrike?`${headlines.bestStrike.strike.toFixed(0)}% BTTS`:"—"}</small></article><article><span>BIGGEST WINNER</span><strong>{headlines.biggest?.biggest!=="—"?headlines.biggest?.name:"—"}</strong><small>{headlines.biggest?.biggest!=="—"?headlines.biggest?.biggest:"Waiting"}</small></article><article><span>BIGGEST CLIMBER</span><strong>{headlines.climber?.positionChange?headlines.climber.name:"—"}</strong><small>{headlines.climber?.positionChange?movement(headlines.climber.positionChange):"No climb yet"}</small></article><article><span>MOST WEEKS #1</span><strong>{headlines.mostWeeks?.weeksAtOne?headlines.mostWeeks.name:"—"}</strong><small>{headlines.mostWeeks?.weeksAtOne?`${headlines.mostWeeks.weeksAtOne} week${headlines.mostWeeks.weeksAtOne===1?"":"s"}`:"No history yet"}</small></article></section>
 <section className="spectatorSection"><div className="spectatorHeading"><div><span>GAMEWEEK RECAP</span><h3>What changed this week?</h3></div></div><div className="publicRecap">{recap.map(line=><p key={line}>{line}</p>)}</div></section>
 <details className="publicStatsCollapse"><summary><span>PLAYER COMPARISON</span><strong>Season performance</strong><small>Tap to expand</small></summary><section className="spectatorSection"><div className="publicStatTable"><div className="publicStatRow head"><span>PLAYER</span><span>POS</span><span>MOVE</span><span>SR%</span><span>PPG</span><span>GAP</span><span>PROJ</span></div>{rows.map(r=><div className="publicStatRow" key={r.id}><strong>{r.name}</strong><span>{r.position}</span><span>{movement(r.positionChange)}</span><span>{r.strike.toFixed(0)}%</span><span>{r.ppg.toFixed(1)}</span><span>{r.gapToLeader?`-${r.gapToLeader}`:"—"}</span><span>{r.projection}</span></div>)}</div><p className="spectatorRule">Projection is a simple current-points-per-scored-gameweek estimate across the scheduled season.</p></section></details>
 <details className="publicStatsCollapse"><summary><span>PLAYER PROFILES</span><strong>Deep stats</strong><small>Tap to expand</small></summary><section className="spectatorSection"><div className="publicPlayerStats">{rows.map(r=><article key={r.id}><header><strong>{r.name}</strong><b>{r.points} pts · {r.position}{r.position===1?"st":r.position===2?"nd":r.position===3?"rd":"th"}</b></header><div><p><span>Strike rate</span><strong>{r.strike.toFixed(0)}%</strong></p><p><span>Points / pick</span><strong>{r.ppg.toFixed(1)}</strong></p><p><span>Current streak</span><strong>{r.currentStreak||"—"}</strong></p><p><span>Best streak</span><strong>{r.bestStreak||"—"}</strong></p><p><span>Avg BTTS odds</span><strong>{r.averageOdds}</strong></p><p><span>Avg winning odds</span><strong>{r.averageWinningOdds}</strong></p><p><span>Biggest winner</span><strong>{r.biggest}</strong></p><p><span>Position change</span><strong>{movement(r.positionChange)}</strong></p><p><span>Highest position</span><strong>{r.highestPosition}</strong></p><p><span>Lowest position</span><strong>{r.lowestPosition}</strong></p><p><span>Weeks at #1</span><strong>{r.weeksAtOne}</strong></p><p><span>Gap to leader</span><strong>{r.gapToLeader?`${r.gapToLeader} pts`:"Leader"}</strong></p><p><span>Season projection</span><strong>{r.projection} pts</strong></p></div><footer><span>Most picked</span><strong>{r.favourite}</strong><span>Best league</span><strong>{r.bestLeague}</strong></footer></article>)}</div></section></details>
 <footer className="spectatorFooter"><div><strong>BOUNCE BTTS LEAGUE</strong><span>Edinburgh · Est 2024</span></div></footer></main>;
}
