import { createAdminClient } from "@/lib/supabase/admin";

export const dynamic="force-dynamic";
type Pred={gameweek_id:string;member_id:string;fixture_id:string;points_awarded:number|null};
type Fixture={id:string;competition:string;country:string;odds_fractional:string|null};
function frac(v:string|null){if(!v)return 0;const m=v.match(/(\d+)\s*\/\s*(\d+)/);return m?Number(m[1])/Math.max(Number(m[2]),1):0}
function competition(f:Fixture){const c=f.competition.toLowerCase();if(f.country==="England"&&c.includes("premier"))return"English Premier League";if(f.country==="England"&&c.includes("championship"))return"English Championship";if(f.country==="England"&&c.includes("league one"))return"English League One";if(f.country==="England"&&c.includes("league two"))return"English League Two";return f.competition;}

export default async function PublicStatsPage(){
 const admin=createAdminClient();
 const [{data:season},{data:profiles},{data:settings}]=await Promise.all([admin.from("seasons").select("id,label").eq("is_current",true).maybeSingle(),admin.from("profiles").select("id,display_name").eq("approved",true).eq("active",true),admin.from("league_settings").select("current_season_label").eq("id",true).maybeSingle()]);
 const {data:gameweeks}=season?.id?await admin.from("gameweeks").select("id,number").eq("season_id",season.id).order("number"):{data:[]};
 const ids=(gameweeks??[]).map(g=>g.id);let predictions:Pred[]=[];
 if(ids.length){const p=await admin.from("predictions").select("gameweek_id,member_id,fixture_id,points_awarded").in("gameweek_id",ids);predictions=(p.data??[]) as Pred[];}
 const fixtureIds=[...new Set(predictions.map(p=>p.fixture_id))];let fixtures:Fixture[]=[];if(fixtureIds.length){const f=await admin.from("fixtures").select("id,competition,country,odds_fractional").in("id",fixtureIds);fixtures=(f.data??[]) as Fixture[];}
 const byFixture=new Map(fixtures.map(f=>[f.id,f]));
 const rows=(profiles??[]).map(profile=>{const picks=predictions.filter(p=>p.member_id===profile.id&&p.points_awarded!=null).sort((a,b)=>(gameweeks??[]).find(g=>g.id===a.gameweek_id)!.number-(gameweeks??[]).find(g=>g.id===b.gameweek_id)!.number);const wins=picks.filter(p=>p.points_awarded===3);const points=picks.reduce((s,p)=>s+Number(p.points_awarded??0),0);let run=0,best=0;for(const p of picks){if(p.points_awarded===3){run++;best=Math.max(best,run)}else run=0}let current=0;for(let i=picks.length-1;i>=0;i--){if(picks[i].points_awarded===3)current++;else break}const winFx=wins.map(p=>byFixture.get(p.fixture_id)).filter(Boolean) as Fixture[];const biggest=[...winFx].sort((a,b)=>frac(b.odds_fractional)-frac(a.odds_fractional))[0]?.odds_fractional??"—";const comps=new Map<string,{p:number,w:number}>();for(const p of picks){const f=byFixture.get(p.fixture_id);if(!f)continue;const k=competition(f);const e=comps.get(k)??{p:0,w:0};e.p++;if(p.points_awarded===3)e.w++;comps.set(k,e)}const favourite=[...comps.entries()].sort((a,b)=>b[1].p-a[1].p)[0]?.[0]??"—";const bestLeague=[...comps.entries()].sort((a,b)=>(b[1].w/Math.max(1,b[1].p))-(a[1].w/Math.max(1,a[1].p)))[0]?.[0]??"—";return{id:profile.id,name:profile.display_name,played:picks.length,wins:wins.length,scoreNil:picks.filter(p=>p.points_awarded===1).length,zeros:picks.filter(p=>p.points_awarded===-1).length,points,strike:picks.length?wins.length/picks.length*100:0,ppg:picks.length?points/picks.length:0,current,best,biggest,favourite,bestLeague}}).sort((a,b)=>b.points-a.points||b.strike-a.strike||a.name.localeCompare(b.name));
 const bestStrike=[...rows].filter(r=>r.played).sort((a,b)=>b.strike-a.strike)[0],bestForm=[...rows].sort((a,b)=>b.current-a.current)[0],biggest=[...rows].sort((a,b)=>frac(b.biggest)-frac(a.biggest))[0];
 return <main className="spectatorPage"><header className="spectatorHero"><div className="spectatorHeroCopy"><span>SEASON {season?.label??settings?.current_season_label??"2026/27"} · LEAGUE STATS</span><h1>BOUNCE</h1><h2>SEASON STORY</h2><p>Form, strike rate, streaks and the numbers behind every pick.</p></div><img src="/assets/st-giles-heart.jpg" alt="Heart of Midlothian pavement mosaic"/></header><nav className="spectatorNav"><a href="/table">Live League</a><a className="active" href="/stats">League Stats</a><a href="/login">Member Login</a></nav><section className="publicStatsLeaders"><article><span>LEAGUE LEADER</span><strong>{rows[0]?.name??"—"}</strong><small>{rows[0]?`${rows[0].points} pts`:"No scores"}</small></article><article><span>BEST FORM</span><strong>{bestForm?.current?bestForm.name:"—"}</strong><small>{bestForm?.current?`${bestForm.current} straight +3s`:"No active streak"}</small></article><article><span>STRIKE RATE</span><strong>{bestStrike?.name??"—"}</strong><small>{bestStrike?`${bestStrike.strike.toFixed(0)}% BTTS`:"—"}</small></article><article><span>BIGGEST WINNER</span><strong>{biggest?.biggest!=="—"?biggest?.name:"—"}</strong><small>{biggest?.biggest!=="—"?biggest?.biggest:"Waiting"}</small></article></section><section className="spectatorSection"><div className="spectatorHeading"><div><span>PLAYER COMPARISON</span><h3>Season performance</h3></div></div><div className="publicStatTable"><div className="publicStatRow head"><span>PLAYER</span><span>SR%</span><span>PPG</span><span>+3</span><span>S-N</span><span>0-0</span><span>STREAK</span></div>{rows.map(r=><div className="publicStatRow" key={r.id}><strong>{r.name}</strong><span>{r.strike.toFixed(0)}%</span><span>{r.ppg.toFixed(1)}</span><span>{r.wins}</span><span>{r.scoreNil}</span><span>{r.zeros}</span><span>{r.current||"—"}</span></div>)}</div></section><section className="spectatorSection"><div className="spectatorHeading"><div><span>PLAYER PROFILES</span><h3>How everyone picks</h3></div></div><div className="publicPlayerStats">{rows.map(r=><article key={r.id}><header><strong>{r.name}</strong><b>{r.points} pts</b></header><div><p><span>Strike rate</span><strong>{r.strike.toFixed(0)}%</strong></p><p><span>Points / pick</span><strong>{r.ppg.toFixed(1)}</strong></p><p><span>Best streak</span><strong>{r.best||"—"}</strong></p><p><span>Biggest winner</span><strong>{r.biggest}</strong></p></div><footer><span>Most picked</span><strong>{r.favourite}</strong><span>Best league</span><strong>{r.bestLeague}</strong></footer></article>)}</div></section><footer className="spectatorFooter"><img src="/assets/st-giles-round.jpg" alt=""/><div><strong>BOUNCE BTTS LEAGUE</strong><span>Edinburgh · Est 2024</span></div></footer></main>;
}
