"use client";

import { useState } from "react";
import styles from "./V2EditorialSections.module.css";

type Tab="about"|"rules"|"instructions"|"members"|"releases";
const releaseRows=[
 {version:"2.0 Preview",date:"13 Sep 2026",summary:"V1 feature-parity completion",changes:["Restored V1 dashboard recap, form windows, league race, sweep tracker, reminder and honours interactions","Restored combined results/table, current player pick status and full historical form/archive behaviour","Added V2 demo/public parity surfaces while retaining canonical scoring, fixture and admin logic"]},
 {version:"1.13.2",date:"10 Sep 2026",summary:"Fixture browser follows selected gameweek",changes:["Two-week Fixtures view follows the global gameweek picker","Browser window anchors to the selected gameweek fixture date","Search, country and competition browsing reload with the selected gameweek"]},
 {version:"1.13.1",date:"10 Sep 2026",summary:"Fixture preload and schedule resilience",changes:["Expanded automatic fixture preloading","Protected no-fixture alerts until provider import attempts are confirmed","Added the Ultimate Admin gameweek-date move control"]},
 {version:"1.13.0",date:"7 Sep 2026",summary:"UI Foundation and architecture migration",changes:["Established behaviour and visual-ownership contracts","Migrated authenticated product surfaces without changing scoring or selection behaviour"]},
 {version:"1.12.1",date:"7 Sep 2026",summary:"Gameweek calendar resilience",changes:["Added low-fixture and zero-fixture warnings","Schedule changes propagate to later normal gameweeks while one-off rounds remain fixed"]},
 {version:"1.12.0",date:"5 Sep 2026",summary:"Shot performance insights",changes:["Added API-Football shot metrics and member finishing insights","Kept scoring and league points unchanged"]},
 {version:"1.11.1",date:"3 Sep 2026",summary:"Member portraits and share identity",changes:["Added member portraits to shares and mobile identity","Retained initials as fallback"]},
];

export default function V2About({seasonLabel,entryFee,role}:{seasonLabel:string;entryFee:number;role:string}){
 const[tab,setTab]=useState<Tab>("about");
 const rules=[{title:"One Pick",text:"Each member chooses one eligible BTTS=YES fixture per gameweek. A fixture cannot be used by two members in the same round."},{title:"Scoring",text:"BTTS lands: +3. A score-nil result: +1. A 0–0: -1. Authoritative settled points always come from the league scoring data."},{title:"Gameweek Window",text:"Opening time, deadline and eligible kickoff rules are controlled per gameweek by the league admin, including one-off and midweek rounds."},{title:"Tie-break",text:"League position uses the canonical tie-break order: points first, then fewer 0–0s, then more BTTS wins, then alphabetical order."},{title:"Entry & Pot",text:`Current season entry is £${entryFee.toFixed(0)} per member. The live prize pot and payment status are maintained through the league admin controls.`},{title:"Bounce Identity",text:"A private Hearts-rooted Edinburgh football league, with the St Giles heart, Tynecastle and the maroon/gold palette forming the visual identity."}];
 const tabs:Array<[Tab,string]>=[["about","About"],["rules","Rules"],["instructions","Instructions"],["members","Members / Admins"],["releases","Release History"]];
 const panelStyle={marginTop:22,display:"grid",gap:0,borderTop:"1px solid rgba(95,31,54,.14)"};
 return <section className={styles.page}><header className={styles.hero}><span>SEASON {seasonLabel}</span><h1>About Bounce</h1><p>Rules, instructions, role guidance and release history — the complete information area retained from V1 inside the V2 identity.</p></header><main className={styles.content}><nav aria-label="About sections" style={{display:"flex",gap:5,overflowX:"auto",paddingBottom:10,borderBottom:"1px solid rgba(95,31,54,.16)"}}>{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setTab(id)} aria-pressed={tab===id} style={{whiteSpace:"nowrap",minHeight:34,padding:"0 11px",border:"1px solid rgba(95,31,54,.18)",background:tab===id?"#5f1f36":"transparent",color:tab===id?"#f6f0e8":"#5f1f36",fontSize:".52rem",fontWeight:850}}>{label}</button>)}</nav>
 {tab==="about"?<><div className={styles.title} style={{marginTop:22}}><div><span className={styles.eyebrow}>THE LEAGUE</span><h2>Bounce BTTS</h2></div><small>Current view · {role==="ultimate_admin"?"Ultimate Admin":role==="admin"?"League Admin":role==="guest"?"Demo":"Member"}</small></div><div className={styles.rules}><article className={styles.rule}><span className={styles.eyebrow}>EST. 2024</span><strong>Private football league</strong><p>One weekly BTTS selection, a shared table and enough statistics, history and banter to make every gameweek matter.</p></article><article className={styles.rule}><span className={styles.eyebrow}>V2 PRINCIPLE</span><strong>New presentation, same league</strong><p>V2 changes navigation and visual hierarchy while canonical scoring, fixture eligibility, history and secured admin behaviour remain authoritative.</p></article></div></>:null}
 {tab==="rules"?<><div className={styles.title} style={{marginTop:22}}><div><span className={styles.eyebrow}>HOW IT WORKS</span><h2>League Rules</h2></div><small>Canonical rules</small></div><div className={styles.rules}>{rules.map((rule,index)=><article className={styles.rule} key={rule.title}><span className={styles.eyebrow}>{String(index+1).padStart(2,"0")}</span><strong>{rule.title}</strong><p>{rule.text}</p></article>)}</div></>:null}
 {tab==="instructions"?<><div className={styles.title} style={{marginTop:22}}><div><span className={styles.eyebrow}>QUICK START</span><h2>Instructions</h2></div><small>Member workflow</small></div><div style={panelStyle}>{[["01","Choose the gameweek","Use the horizontal gameweek rail. Dashboard, Fixtures, Results and Stats follow the selected gameweek."],["02","Make your pick","Open Make My Pick, search or browse eligible fixtures, then choose one untaken BTTS selection before the deadline."],["03","Check the league","Dashboard shows your pick, everyone’s selections, live state, the table, recap and form. Results provides the combined gameweek view."],["04","Review deeper stats","Stat Centre contains league analytics, player tendencies, form and records. League History preserves completed seasons and weekly archives."],["05","Share","Use the share actions for picks, combined results, table, form, recap, race and sweep tracker. iPhone/iPad use the native share sheet where supported."]].map(([number,title,text])=><article key={number} style={{display:"grid",gridTemplateColumns:"44px minmax(0,1fr)",gap:12,padding:"15px 0",borderBottom:"1px solid rgba(95,31,54,.09)"}}><b style={{color:"#8e5b35",fontSize:".55rem"}}>{number}</b><div><strong style={{color:"#431326",fontFamily:"Georgia,serif",fontSize:".9rem"}}>{title}</strong><p style={{margin:"5px 0 0",color:"#746d67",fontSize:".6rem",lineHeight:1.5}}>{text}</p></div></article>)}</div></>:null}
 {tab==="members"?<><div className={styles.title} style={{marginTop:22}}><div><span className={styles.eyebrow}>ACCESS & RESPONSIBILITY</span><h2>Members / Admins</h2></div><small>Role guide</small></div><div className={styles.rules}><article className={styles.rule}><span className={styles.eyebrow}>MEMBER</span><strong>Play and explore</strong><p>Make/change your own pick while open; view fixtures, results, statistics, players, history and all member share experiences.</p></article><article className={styles.rule}><span className={styles.eyebrow}>LEAGUE ADMIN</span><strong>Run the gameweek</strong><p>Manage gameweek timing, selections, fixtures/provider data, results, recalculation, alerts and normal league operations.</p></article><article className={styles.rule}><span className={styles.eyebrow}>ULTIMATE ADMIN</span><strong>Full league control</strong><p>Includes member/account management, credentials, payments, portraits, emulation, season creation and advanced safety controls.</p></article><article className={styles.rule}><span className={styles.eyebrow}>DEMO</span><strong>Read-only perspectives</strong><p>Demo Mode can switch between member and admin perspectives without changing data or exposing credentials/private operational information.</p></article></div></>:null}
 {tab==="releases"?<><div className={styles.title} style={{marginTop:22}}><div><span className={styles.eyebrow}>PRODUCT HISTORY</span><h2>Release History</h2></div><small>V1 continuity → V2</small></div><div style={panelStyle}>{releaseRows.map(row=><details key={row.version} style={{borderBottom:"1px solid rgba(95,31,54,.09)",padding:"3px 0"}} open={row.version==="2.0 Preview"}><summary style={{cursor:"pointer",display:"grid",gridTemplateColumns:"105px minmax(0,1fr) auto",gap:10,alignItems:"center",minHeight:48,listStyle:"none"}}><strong style={{color:"#431326",fontFamily:"Georgia,serif",fontSize:".78rem"}}>v{row.version}</strong><span style={{color:"#34252c",fontSize:".58rem",fontWeight:800}}>{row.summary}</span><small style={{color:"#746d67",fontSize:".48rem"}}>{row.date}</small></summary><div style={{padding:"0 0 12px 105px",color:"#746d67",fontSize:".56rem",lineHeight:1.5}}>{row.changes.map(change=><p key={change} style={{margin:"4px 0"}}>• {change}</p>)}</div></details>)}</div></>:null}
 </main><footer className={styles.footer}>Bounce BTTS · Hearts · Edinburgh · {seasonLabel} · V2 preview</footer></section>}
