"use client";

import { useState } from "react";
import { historicalSeasons, rollOfHonour } from "@/lib/history-data";
import V2CurrentSeasonArchive from "./V2CurrentSeasonArchive";
import styles from "./V2EditorialSections.module.css";

function pointLabel(value:number){return `${value>0?"+":""}${value} pt${Math.abs(value)===1?"":"s"}`}

export default function V2LeagueHistory({seasonLabel}:{seasonLabel:string}){
  const currentChampion=rollOfHonour[rollOfHonour.length-1];
  const[honoursOpen,setHonoursOpen]=useState(false);
  const[formRange,setFormRange]=useState<6|12|18>(6);
  return <section className={styles.page}>
    <header className={styles.hero}><span>BOUNCE ARCHIVE · {seasonLabel}</span><h1>League History</h1><p>The permanent record of Bounce BTTS: current-season gameweek detail, champions, preserved final tables, selectable historic form windows and the full weekly archive.</p></header>
    <main className={styles.content}>
      <div className={styles.title}><div><span className={styles.eyebrow}>ROLL OF HONOUR</span><h2>Bounce Cup</h2></div><button type="button" onClick={()=>setHonoursOpen(value=>!value)} aria-expanded={honoursOpen} style={{minHeight:38,border:"1px solid rgba(95,31,54,.2)",background:"transparent",color:"#5f1f36",padding:"0 11px",fontSize:".54rem",fontWeight:850,display:"flex",alignItems:"center",gap:8}}><img src="/assets/bounce-cup.png" alt="" style={{width:28,height:28,objectFit:"contain"}}/>{honoursOpen?"Hide honours":"View honours"}</button></div>
      {currentChampion?<div className={styles.champion}><div><span className={styles.eyebrow}>REIGNING CHAMPION · {currentChampion.season}</span><strong>{currentChampion.winner}</strong><small>Current holder of the Bounce Cup</small></div><b>{currentChampion.points} PTS</b></div>:null}
      {honoursOpen?<div style={{display:"grid",margin:"-18px 0 28px",borderBottom:"1px solid rgba(95,31,54,.14)"}}>{[...rollOfHonour].reverse().map(row=><div key={row.season} style={{display:"grid",gridTemplateColumns:"90px minmax(0,1fr) auto",gap:10,alignItems:"center",minHeight:42,borderTop:"1px solid rgba(95,31,54,.08)",fontSize:".58rem",color:"#746d67"}}><span>{row.season}</span><strong style={{color:"#34252c",fontFamily:"Georgia,serif",fontSize:".76rem"}}>{row.winner}</strong><b style={{color:"#8e5b35",fontSize:".52rem"}}>{row.points} PTS</b></div>)}</div>:null}
      <V2CurrentSeasonArchive/>
      <div style={{display:"flex",justifyContent:"flex-end",margin:"0 0 8px"}}><label style={{display:"flex",alignItems:"center",gap:8,color:"#746d67",fontSize:".52rem"}}>Historic form window<select value={formRange} onChange={event=>setFormRange(Number(event.target.value) as 6|12|18)} style={{minHeight:32,border:"1px solid rgba(95,31,54,.2)",background:"transparent",color:"#5f1f36",padding:"0 8px",fontWeight:800}}><option value={6}>6 weeks</option><option value={12}>12 weeks</option><option value={18}>18 weeks</option></select></label></div>
      {historicalSeasons.slice().reverse().map((season,index)=><details className={styles.season} key={season.season} open={index===0}>
        <summary><strong>{season.season} · {season.winner}</strong><span>{season.weeks} gameweeks · {season.finalTable.length} players</span></summary>
        <p className={styles.note}>{season.scoringNote} {season.tablePointsNote}</p>
        <div className={`${styles.historyRow} ${styles.historyHead}`}><span>#</span><span>Player</span><span>P</span><span>W</span><span>S-N</span><span>L</span><span>PTS</span></div>
        <div className={styles.historyTable}>{season.finalTable.map((row,pos)=><div className={styles.historyRow} key={row.name}><span>{pos+1}</span><strong>{row.name}</strong><span>{row.played}</span><span>{row.wins}</span><span>{row.scoreNil}</span><span>{row.losses}</span><b>{row.points}</b></div>)}</div>
        <section style={{marginTop:24,borderTop:"1px solid rgba(95,31,54,.15)",paddingTop:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"baseline",marginBottom:10}}><div><span className={styles.eyebrow}>HISTORIC FORM</span><strong style={{display:"block",marginTop:3,color:"#431326",fontFamily:"Georgia,serif",fontSize:"1rem"}}>Final {Math.min(formRange,season.weeks)} gameweeks</strong></div><small style={{color:"#746d67",fontSize:".5rem"}}>GW {Math.max(1,season.weeks-formRange+1)}–{season.weeks}</small></div><div style={{overflowX:"auto"}}><div style={{minWidth:620}}>{(()=>{const start=Math.max(0,season.weeks-formRange);const weeks=Array.from({length:season.weeks-start},(_,i)=>start+i+1);const rows=season.weekly.map(player=>({name:player.name,values:player.weeklyAwardedPoints.slice(start),total:player.weeklyAwardedPoints.slice(start).reduce((sum,value)=>sum+value,0)})).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name));const template=`minmax(120px,1.4fr) repeat(${weeks.length},minmax(40px,.55fr)) 54px`;return <><div style={{display:"grid",gridTemplateColumns:template,gap:3,minHeight:30,alignItems:"center",borderBottom:"1px solid rgba(95,31,54,.14)",color:"#8e5b35",fontSize:".4rem",fontWeight:900,textTransform:"uppercase"}}><strong>Player</strong>{weeks.map(week=><span key={week} style={{textAlign:"center"}}>GW{week}</span>)}<b style={{textAlign:"right"}}>Total</b></div>{rows.map(row=><div key={row.name} style={{display:"grid",gridTemplateColumns:template,gap:3,minHeight:38,alignItems:"center",borderBottom:"1px solid rgba(95,31,54,.07)",fontSize:".5rem",color:"#746d67"}}><strong style={{color:"#34252c",fontFamily:"Georgia,serif",fontSize:".66rem"}}>{row.name}</strong>{row.values.map((value,i)=><span key={`${row.name}-${weeks[i]}`} style={{textAlign:"center",fontWeight:800,color:value>=2?"#35634a":value<0?"#963b49":"#8b661d"}}>{value>0?`+${value}`:value}</span>)}<b style={{textAlign:"right",color:"#5f1f36"}}>{row.total>0?`+${row.total}`:row.total}</b></div>)}</>})()}</div></div></section>
        <details style={{marginTop:22,borderTop:"1px solid rgba(95,31,54,.15)",paddingTop:6}}>
          <summary style={{minHeight:48}}><strong>Weekly archive</strong><span>GW 1–{season.weeks} · independently expandable</span></summary>
          <div style={{display:"grid",gap:8,padding:"12px 0 4px"}}>{Array.from({length:season.weeks},(_,weekIndex)=>{const week=weekIndex+1;const rows=season.weekly.map(player=>({name:player.name,points:player.weeklyAwardedPoints[weekIndex]})).filter(row=>typeof row.points==="number");return <details key={week} style={{borderBottom:"1px solid rgba(95,31,54,.09)",paddingBottom:6}}><summary style={{minHeight:42}}><strong>Gameweek {week}</strong><span>{rows.length} recorded result{rows.length===1?"":"s"}</span></summary><div style={{display:"grid",padding:"4px 0 8px"}}>{rows.map(row=><div key={row.name} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:12,alignItems:"center",minHeight:34,borderBottom:"1px solid rgba(95,31,54,.055)",fontSize:".58rem",color:"#746d67"}}><strong style={{color:"#34252c",fontFamily:"Georgia,serif",fontSize:".7rem"}}>{row.name}</strong><b style={{color:row.points===3||row.points===2?"#35634a":row.points<0?"#963b49":"#8b661d"}}>{pointLabel(row.points)}</b></div>)}</div></details>})}</div>
        </details>
      </details>)}
    </main>
    <footer className={styles.footer}>Bounce BTTS · current-season detail · Roll of Honour · historical form + weekly archive</footer>
  </section>
}
