"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import styles from "./V2ShotPerformance.module.css";

type Profile={id:string;display_name:string;active:boolean;role:string};
type Prediction={member_id:string;fixture_id:string;points_awarded:number|null};
type Fixture={id:string};
type FixtureStats={id:string;homeShots:number|null;awayShots:number|null;homeShotsOnTarget:number|null;awayShotsOnTarget:number|null;homeScore:number|null;awayScore:number|null};
type Payload={fixtures?:FixtureStats[];coverage?:number;finished?:number;pending?:number;error?:string};
type Row={id:string;name:string;picks:number;shots:number;shotsOnTarget:number;goals:number;avgShots:number;avgShotsOnTarget:number;avgGoals:number;conversion:number|null;shotsPerGoal:number|null};

async function accessToken(){const{data}=await createClient().auth.getSession();return data.session?.access_token??""}
function rounded(value:number,digits=1){const scale=10**digits;return Math.round(value*scale)/scale}
function leader(rows:Row[],metric:(row:Row)=>number|null,direction:"high"|"low"="high"){const scored=rows.map(row=>({row,value:metric(row)})).filter((item):item is {row:Row;value:number}=>item.value!=null&&Number.isFinite(item.value)).map(item=>({...item,displayedValue:rounded(item.value)}));if(!scored.length)return null;const target=direction==="high"?Math.max(...scored.map(item=>item.displayedValue)):Math.min(...scored.map(item=>item.displayedValue));return{names:scored.filter(item=>item.displayedValue===target).map(item=>item.row.name).sort((a,b)=>a.localeCompare(b)),value:target}}

export default function V2ShotPerformance({profiles,predictions,fixtures}:{profiles:Profile[];predictions:Prediction[];fixtures:Fixture[]}){
 const[payload,setPayload]=useState<Payload|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function load(){if(loading)return;setLoading(true);setError("");try{const response=await fetch("/api/fixture-stats",{headers:{authorization:`Bearer ${await accessToken()}`},cache:"no-store"});const json=await response.json() as Payload;if(!response.ok)throw new Error(json.error??"Could not load match statistics");setPayload(json)}catch(reason){setError(reason instanceof Error?reason.message:"Could not load match statistics")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const rows=useMemo<Row[]>(()=>{const statsMap=new Map((payload?.fixtures??[]).map(row=>[row.id,row]));const fixtureIds=new Set(fixtures.map(f=>f.id));return profiles.filter(profile=>profile.active&&profile.role!=="guest").map(profile=>{const usable=predictions.filter(prediction=>prediction.member_id===profile.id&&prediction.points_awarded!==null&&fixtureIds.has(prediction.fixture_id)).map(prediction=>statsMap.get(prediction.fixture_id)).filter((stats):stats is FixtureStats=>Boolean(stats&&stats.homeShots!=null&&stats.awayShots!=null&&stats.homeShotsOnTarget!=null&&stats.awayShotsOnTarget!=null));const shots=usable.reduce((sum,item)=>sum+Number(item.homeShots)+Number(item.awayShots),0),shotsOnTarget=usable.reduce((sum,item)=>sum+Number(item.homeShotsOnTarget)+Number(item.awayShotsOnTarget),0),goals=usable.reduce((sum,item)=>sum+Number(item.homeScore??0)+Number(item.awayScore??0),0),picks=usable.length;return{id:profile.id,name:profile.display_name,picks,shots,shotsOnTarget,goals,avgShots:picks?shots/picks:0,avgShotsOnTarget:picks?shotsOnTarget/picks:0,avgGoals:picks?goals/picks:0,conversion:shots>0?(goals/shots)*100:null,shotsPerGoal:goals>0?shots/goals:null}}).filter(row=>row.picks>0).sort((a,b)=>b.picks-a.picks||a.name.localeCompare(b.name))},[payload,profiles,predictions,fixtures]);
 const awards=[{label:"CHANCE MAGNET",leader:leader(rows,row=>row.avgShots),detail:"avg total shots"},{label:"SHARPSHOOTER",leader:leader(rows,row=>row.avgShotsOnTarget),detail:"avg shots on target"},{label:"CLINICAL PICKER",leader:leader(rows,row=>row.conversion),detail:"% shot conversion"},{label:"SHOT SHY",leader:leader(rows,row=>row.avgShotsOnTarget,"low"),detail:"avg shots on target"},{label:"COLDEST FINISHER",leader:leader(rows,row=>row.conversion,"low"),detail:"% shot conversion"}];
 return <section className={styles.shell}><div className={styles.head}><div><span>SHOT PERFORMANCE</span><h3>Match Selection Analytics</h3><p>Direct fixture statistics from finished selected matches. Shot figures combine both teams in each selected fixture.</p></div><button type="button" onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh stats"}</button></div>{error?<div className={`${styles.notice} ${styles.error}`}>{error}</div>:null}{!payload&&!error?<div className={styles.notice}>Loading shot-performance data…</div>:null}{payload?<><div className={styles.awards}>{awards.map(item=><article className={styles.award} key={item.label}><span>{item.label}</span><strong>{item.leader?.names.join(" / ")??"—"}</strong><small>{item.leader?`${item.leader.value} ${item.detail}`:"Awaiting covered fixtures"}</small></article>)}</div><div className={styles.table}><div className={`${styles.row} ${styles.header}`}><strong>Member</strong><span>Covered</span><span>Avg shots</span><span>Avg SoT</span><span>Avg goals</span><span>Conversion</span></div>{rows.map(row=><div className={styles.row} key={row.id}><strong>{row.name}</strong><b>{row.picks}</b><b>{rounded(row.avgShots)}</b><b>{rounded(row.avgShotsOnTarget)}</b><b>{rounded(row.avgGoals)}</b><b>{row.conversion==null?"—":`${rounded(row.conversion)}%`}</b></div>)}</div><div className={styles.coverage}>{Number(payload.coverage??0)}/{Number(payload.finished??0)} finished selected games currently have complete shot data{Number(payload.pending??0)>0?` · ${payload.pending} await backfill`:""}. Conversion = goals ÷ shots.</div></>:null}</section>
}
