"use client";

import { useState } from "react";
import { drawShareAvatar, findSharePortrait, loadSharePortraits } from "@/lib/share-portraits";
import { SHARE_BRAND, drawShareFooter, drawShareMasthead, drawSharePaper, loadShareBrandArtwork } from "@/lib/share-brand";

type Props = { title: string; subtitle?: string; columns: string[]; rows: Array<Array<string | number>>; fileName: string; label: string; compact?: boolean };
function fitText(ctx:CanvasRenderingContext2D,value:string,maxWidth:number){if(ctx.measureText(value).width<=maxWidth)return value;let text=value;while(text.length>1&&ctx.measureText(`${text}…`).width>maxWidth)text=text.slice(0,-1);return `${text}…`}
async function createImage({title,subtitle,columns,rows}:Pick<Props,"title"|"subtitle"|"columns"|"rows">){
  const [portraits,artwork]=await Promise.all([loadSharePortraits(),loadShareBrandArtwork()]);
  const width=1200,headerHeight=240,rowHeight=72,footerHeight=120,height=headerHeight+Math.max(rows.length,1)*rowHeight+footerHeight;
  const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Unable to create share image.");
  drawSharePaper(ctx,width,height,artwork);drawShareMasthead(ctx,width,{eyebrow:"BOUNCE BTTS LEAGUE",title,subtitle,artwork,top:48,left:70});
  const left=62,right=1138,tableWidth=right-left,colWidth=tableWidth/Math.max(columns.length,1);
  ctx.fillStyle="rgba(95,31,54,.055)";ctx.fillRect(left,headerHeight-4,tableWidth,46);ctx.strokeStyle="rgba(95,31,54,.16)";ctx.beginPath();ctx.moveTo(left,headerHeight+42);ctx.lineTo(right,headerHeight+42);ctx.stroke();ctx.fillStyle="#8e5b35";ctx.font="900 15px Arial,sans-serif";columns.forEach((column,index)=>ctx.fillText(fitText(ctx,column,colWidth-18),left+index*colWidth+10,headerHeight+25));
  if(!rows.length){ctx.fillStyle=SHARE_BRAND.muted;ctx.font="600 22px Arial,sans-serif";ctx.fillText("No data to share yet.",70,headerHeight+95)}
  rows.forEach((row,rowIndex)=>{const y=headerHeight+42+rowIndex*rowHeight;if(rowIndex===0){ctx.fillStyle="rgba(183,141,54,.075)";ctx.fillRect(left,y,tableWidth,rowHeight)}row.forEach((value,colIndex)=>{const text=String(value);const portrait=typeof value==="string"?findSharePortrait(portraits,null,text):null;const cellX=left+colIndex*colWidth+10;ctx.fillStyle=colIndex===row.length-1?SHARE_BRAND.maroon:SHARE_BRAND.ink;ctx.font=colIndex===0||colIndex===row.length-1?"800 18px Arial,sans-serif":"600 18px Arial,sans-serif";if(portrait){drawShareAvatar(ctx,portraits,{id:portrait.id,name:text,x:cellX+17,y:y+36,size:34,border:SHARE_BRAND.goldSoft,background:SHARE_BRAND.maroon});ctx.fillText(fitText(ctx,text,colWidth-58),cellX+43,y+43)}else ctx.fillText(fitText(ctx,text,colWidth-18),cellX,y+43)});ctx.strokeStyle="rgba(95,31,54,.09)";ctx.beginPath();ctx.moveTo(left,y+rowHeight);ctx.lineTo(right,y+rowHeight);ctx.stroke()});
  drawShareFooter(ctx,width,height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error("Image creation failed.")),"image/jpeg",.94));return blob;
}
export default function DataShareButton(props:Props){const[busy,setBusy]=useState(false);async function share(){if(busy)return;setBusy(true);try{const blob=await createImage(props);const file=new File([blob],props.fileName,{type:"image/jpeg"});const data:ShareData={title:props.title,text:`Bounce BTTS League — ${props.title}`,files:[file]};const nav=navigator as Navigator&{canShare?:(data:ShareData)=>boolean};if(navigator.share&&(!nav.canShare||nav.canShare({files:[file]})))await navigator.share(data);else{const url=URL.createObjectURL(file);const a=document.createElement("a");a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}}finally{setBusy(false)}}return <button type="button" className={`dataShareButton shareCompactWhatsApp ${props.compact?"compact":""}`} onClick={share} disabled={busy} aria-label={`${props.label} to WhatsApp`}>{busy?"Creating…":"Share to WhatsApp"}</button>}
