import { sortFixtureSharePicks } from "./shareFixtureSort";
import { drawShareAvatar, loadSharePortraits, type SharePortraitLookup } from "@/lib/share-portraits";
import { SHARE_BRAND, drawShareFooter, drawShareMasthead, drawSharePaper, loadShareBrandArtwork, type ShareBrandArtwork } from "@/lib/share-brand";

export type FixtureSharePick = {
  player: string;
  homeTeam: string;
  awayTeam: string;
  competition: string;
  kickoffAt: string;
  odds: string | null;
  status?: string | null;
  homeScore?: number | null;
  awayScore?: number | null;
  elapsed?: number | null;
};

export type FixtureShareStanding = {
  name: string;
  played: number;
  wins: number;
  oneSided: number;
  zeroZeroCount: number;
  points: number;
};

type PickState = "win" | "scoreNil" | "zeroZero" | "pending";
const liveStatuses=new Set(["1H","2H","ET","P","BT","INT"]);
const finishedStatuses=new Set(["FT","AET","PEN"]);

function scoreLabel(pick:FixtureSharePick){const status=pick.status??"";if(pick.homeScore==null||pick.awayScore==null)return "";if(liveStatuses.has(status))return `${pick.homeScore}–${pick.awayScore} · ${pick.elapsed!=null?`${pick.elapsed}′`:"LIVE"}`;if(status==="HT")return `${pick.homeScore}–${pick.awayScore} · HT`;if(finishedStatuses.has(status))return `${pick.homeScore}–${pick.awayScore} · ${status}`;return `${pick.homeScore}–${pick.awayScore}`}
function pickState(pick:FixtureSharePick):{text:string;state:PickState}{const finished=finishedStatuses.has(pick.status??"");const home=pick.homeScore,away=pick.awayScore;if(home==null||away==null)return {text:"PENDING",state:"pending"};if(home===0&&away===0)return {text:"0-0  -1",state:"zeroZero"};if(home>0&&away>0)return {text:finished?"WON  +3":"WON",state:"win"};return {text:finished?"SCORE-NIL  +1":"SCORE-NIL LIVE",state:"scoreNil"}}
function colours(state:PickState){if(state==="win")return {fill:"#dceee2",stroke:"#84ad92",text:"#285f40"};if(state==="scoreNil")return {fill:"#f1e3aa",stroke:"#c7a74d",text:"#77530f"};if(state==="zeroZero")return {fill:"#efd3d8",stroke:"#c6848e",text:"#8d3441"};return {fill:"#e4ddd6",stroke:"#b8ada4",text:"#6e6660"}}
function formatFixtureOddsDisplay(value:string|null|undefined){if(!value)return null;const match=value.trim().match(/^(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)$/);if(!match)return value;const numerator=Number(match[1]),denominator=Number(match[2]);if(!Number.isFinite(numerator)||!Number.isFinite(denominator)||denominator<=0)return value;return `${(numerator/denominator).toFixed(2)}/1`}
function combinedFractionalOdds(picks:FixtureSharePick[]){if(!picks.length)return null;let combinedDecimal=1;for(const pick of picks){const match=pick.odds?.trim().match(/^(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)$/);if(!match)return null;const numerator=Number(match[1]),denominator=Number(match[2]);if(!Number.isFinite(numerator)||!Number.isFinite(denominator)||denominator<=0)return null;combinedDecimal*=1+numerator/denominator}const fractionalTotal=combinedDecimal-1;if(!Number.isFinite(fractionalTotal)||fractionalTotal<0)return null;return `${fractionalTotal.toFixed(2)}/1`}
function drawCombinedOdds(ctx:CanvasRenderingContext2D,picks:FixtureSharePick[],y:number){const odds=combinedFractionalOdds(picks);ctx.fillStyle=SHARE_BRAND.maroon;ctx.font="800 21px Arial,sans-serif";ctx.textAlign="right";ctx.fillText(odds?`Combined BTTS odds  ${odds}`:"Combined BTTS odds unavailable",1130,y);ctx.textAlign="left"}

function drawHeader(ctx:CanvasRenderingContext2D,width:number,seasonLabel:string,gameweekNumber:number,title:string,artwork:ShareBrandArtwork){drawShareMasthead(ctx,width,{eyebrow:`Season ${seasonLabel} · Gameweek ${gameweekNumber}`,title,subtitle:"Bounce BTTS League · selected fixtures",artwork,top:48,left:70})}

export function drawFixtureRows(ctx:CanvasRenderingContext2D,picks:FixtureSharePick[],startY:number,portraits:SharePortraitLookup){const rows=sortFixtureSharePicks(picks);const rowHeight=112;rows.forEach((pick,index)=>{const y=startY+index*rowHeight;ctx.strokeStyle="rgba(95,31,54,.13)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(64,y+rowHeight-1);ctx.lineTo(1136,y+rowHeight-1);ctx.stroke();if(index===0){ctx.fillStyle="rgba(183,141,54,.055)";ctx.fillRect(58,y+4,1084,rowHeight-8)}drawShareAvatar(ctx,portraits,{name:pick.player,x:91,y:y+42,size:38,border:SHARE_BRAND.goldSoft,background:SHARE_BRAND.maroon});ctx.fillStyle=SHARE_BRAND.ink;ctx.font="800 24px Arial,sans-serif";ctx.fillText(pick.player.slice(0,20),120,y+49);ctx.fillStyle=SHARE_BRAND.maroonDeep;ctx.font="700 25px Georgia,serif";ctx.fillText(`${pick.homeTeam} v ${pick.awayTeam}`.slice(0,42),330,y+42);const live=scoreLabel(pick);ctx.fillStyle=live?SHARE_BRAND.maroon:"#7c746d";ctx.font=live?"800 18px Arial,sans-serif":"600 16px Arial,sans-serif";ctx.fillText(live||pick.competition.slice(0,42),330,y+73);ctx.fillStyle=SHARE_BRAND.muted;ctx.font="700 16px Arial,sans-serif";const kickoff=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(pick.kickoffAt));ctx.fillText(kickoff,120,y+76);const outcome=pickState(pick),tone=colours(outcome.state);ctx.fillStyle=tone.fill;ctx.fillRect(795,y+52,190,31);ctx.strokeStyle=tone.stroke;ctx.strokeRect(795,y+52,190,31);ctx.fillStyle=tone.text;ctx.font="800 14px Arial,sans-serif";ctx.textAlign="center";ctx.fillText(outcome.text,890,y+73);ctx.textAlign="left";ctx.fillStyle=SHARE_BRAND.maroon;ctx.font="800 28px Georgia,serif";ctx.fillText(formatFixtureOddsDisplay(pick.odds)??"—",1010,y+58)});return startY+Math.max(rows.length,1)*rowHeight}
function toFile(canvas:HTMLCanvasElement,name:string){return new Promise<File>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(new File([blob],name,{type:"image/jpeg"})):reject(new Error("Image creation failed.")),"image/jpeg",.94))}

export async function createFixtureShareImage(gameweekNumber:number,seasonLabel:string,picks:FixtureSharePick[]){const [portraits,artwork]=await Promise.all([loadSharePortraits(),loadShareBrandArtwork()]);const width=1200,headerHeight=230,footerHeight=132,rowHeight=112;const height=headerHeight+Math.max(picks.length,1)*rowHeight+footerHeight;const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Unable to create image.");drawSharePaper(ctx,width,height,artwork);drawHeader(ctx,width,seasonLabel,gameweekNumber,"Selected Fixtures",artwork);const end=drawFixtureRows(ctx,picks,headerHeight,portraits);if(!picks.length){ctx.fillStyle=SHARE_BRAND.muted;ctx.font="600 25px Arial,sans-serif";ctx.fillText("No selections submitted yet.",70,headerHeight+65)}drawCombinedOdds(ctx,picks,end+32);ctx.fillStyle=SHARE_BRAND.muted;ctx.font="500 16px Arial,sans-serif";ctx.fillText("Live score and pick status reflect the latest in-app refresh.",70,end+64);drawShareFooter(ctx,width,height);return toFile(canvas,`bounce-btts-gw${gameweekNumber}-fixtures.jpg`)}

export async function createCombinedShareImage(gameweekNumber:number,seasonLabel:string,picks:FixtureSharePick[],standings:FixtureShareStanding[]){const [portraits,artwork]=await Promise.all([loadSharePortraits(),loadShareBrandArtwork()]);const width=1200,headerHeight=230,rowHeight=112,tableHead=78,tableRow=62,footer=126;const fixtureHeight=Math.max(picks.length,1)*rowHeight;const tableHeight=tableHead+Math.max(standings.length,1)*tableRow;const height=headerHeight+fixtureHeight+54+tableHeight+footer;const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Unable to create image.");drawSharePaper(ctx,width,height,artwork);drawHeader(ctx,width,seasonLabel,gameweekNumber,"Fixtures + Table",artwork);const fixtureEnd=drawFixtureRows(ctx,picks,headerHeight,portraits);const tableY=fixtureEnd+54;
  const fadeStart=fixtureEnd-18;const fadeEnd=tableY+54;const fade=ctx.createLinearGradient(0,fadeStart,0,fadeEnd);fade.addColorStop(0,"rgba(243,234,223,0)");fade.addColorStop(.45,"rgba(243,234,223,.68)");fade.addColorStop(1,SHARE_BRAND.paper);ctx.fillStyle=fade;ctx.fillRect(0,fadeStart,width,fadeEnd-fadeStart);ctx.fillStyle=SHARE_BRAND.paper;ctx.fillRect(0,fadeEnd,width,height-fadeEnd);
  ctx.fillStyle=SHARE_BRAND.maroonDeep;ctx.font="700 29px Georgia,serif";ctx.fillText("League Table",70,tableY+30);ctx.strokeStyle="rgba(95,31,54,.18)";ctx.beginPath();ctx.moveTo(70,tableY+48);ctx.lineTo(1130,tableY+48);ctx.stroke();const cols=[82,160,690,785,875,975,1080];ctx.fillStyle="#8e5b35";ctx.font="800 15px Arial,sans-serif";["POS","PLAYER","P","W","S-N","0-0","PTS"].forEach((label,i)=>ctx.fillText(label,cols[i],tableY+75));standings.forEach((row,index)=>{const y=tableY+tableHead+index*tableRow;if(index===0){ctx.fillStyle="rgba(183,141,54,.12)";ctx.fillRect(60,y+4,1080,tableRow-8)}ctx.strokeStyle="rgba(95,31,54,.1)";ctx.beginPath();ctx.moveTo(60,y+tableRow);ctx.lineTo(1140,y+tableRow);ctx.stroke();ctx.fillStyle=SHARE_BRAND.ink;ctx.font="700 20px Arial,sans-serif";ctx.fillText(String(index+1),cols[0],y+40);drawShareAvatar(ctx,portraits,{name:row.name,x:176,y:y+32,size:34,border:SHARE_BRAND.goldSoft,background:SHARE_BRAND.maroon});ctx.fillStyle=SHARE_BRAND.ink;ctx.font="700 21px Arial,sans-serif";ctx.fillText(row.name.slice(0,30),199,y+40);ctx.font="600 19px Arial,sans-serif";ctx.fillText(String(row.played),cols[2],y+40);ctx.fillText(String(row.wins),cols[3],y+40);ctx.fillText(String(row.oneSided),cols[4],y+40);ctx.fillText(String(row.zeroZeroCount),cols[5],y+40);ctx.fillStyle=SHARE_BRAND.maroon;ctx.font="800 23px Georgia,serif";ctx.fillText(String(row.points),cols[6],y+40)});const footerY=tableY+tableHeight;drawCombinedOdds(ctx,picks,footerY+20);ctx.fillStyle=SHARE_BRAND.muted;ctx.font="500 16px Arial,sans-serif";ctx.fillText("Fixtures above use the same live/result status as the app.",70,footerY+50);drawShareFooter(ctx,width,height);return toFile(canvas,`bounce-btts-gw${gameweekNumber}-fixtures-table.jpg`)}
