"use client";

import { useState } from "react";
import { drawShareAvatar, loadSharePortraits } from "@/lib/share-portraits";
import { SHARE_BRAND, drawShareFooter, drawShareMasthead, drawSharePaper, loadShareBrandArtwork } from "@/lib/share-brand";

type SubmittedPick = { name: string; fixture: string };
type Props = { gameweekNumber:number; seasonLabel:string; deadline:string; missingNames:string[]; submittedPicks:SubmittedPick[]; disabled?:boolean };
function deadlineLabel(value:string){return new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value))}
async function canvasBlob(canvas:HTMLCanvasElement){return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Could not create reminder image.")),"image/png"))}
function fitText(ctx:CanvasRenderingContext2D,value:string,maxWidth:number,start:number,min=17){let size=start;while(size>min){ctx.font=`800 ${size}px Arial`;if(ctx.measureText(value).width<=maxWidth)break;size-=1}return size}

export default function ReminderShareButton({gameweekNumber,seasonLabel,deadline,missingNames,submittedPicks,disabled}:Props){
 const[sharing,setSharing]=useState(false);
 async function share(){if(sharing||disabled||!missingNames.length)return;setSharing(true);try{const [portraits,artwork]=await Promise.all([loadSharePortraits(),loadShareBrandArtwork()]);const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Image sharing is not supported in this browser.");drawSharePaper(ctx,1080,1350,artwork);drawShareMasthead(ctx,1080,{eyebrow:`Season ${seasonLabel} · Gameweek ${gameweekNumber}`,title:"Pick Reminder",subtitle:"Bounce BTTS League · selections still outstanding",artwork,top:48,left:62});
 ctx.fillStyle="rgba(183,141,54,.10)";ctx.fillRect(62,230,956,104);ctx.strokeStyle="rgba(95,31,54,.16)";ctx.strokeRect(62,230,956,104);ctx.fillStyle="#8e5b35";ctx.font="900 20px Arial";ctx.fillText("DEADLINE",88,269);ctx.fillStyle=SHARE_BRAND.maroonDeep;ctx.font="700 31px Georgia";ctx.fillText(deadlineLabel(deadline),88,310);
 const leftX=62,rightX=558,colW=460,cardY=380,cardH=780;const drawPanel=(x:number,title:string,subtitle:string,tone:string)=>{ctx.fillStyle="rgba(255,255,255,.34)";ctx.fillRect(x,cardY,colW,cardH);ctx.strokeStyle="rgba(95,31,54,.15)";ctx.strokeRect(x,cardY,colW,cardH);ctx.fillStyle=tone;ctx.font="900 19px Arial";ctx.fillText(title,x+28,cardY+42);ctx.fillStyle=SHARE_BRAND.muted;ctx.font="700 15px Arial";ctx.fillText(subtitle,x+28,cardY+68);ctx.strokeStyle="rgba(95,31,54,.12)";ctx.beginPath();ctx.moveTo(x+28,cardY+86);ctx.lineTo(x+colW-28,cardY+86);ctx.stroke()};drawPanel(leftX,"STILL TO PICK",`${missingNames.length} outstanding`,SHARE_BRAND.maroon);drawPanel(rightX,"PICKS IN",`${submittedPicks.length} submitted`,SHARE_BRAND.success);
 const missingRowH=Math.min(118,640/Math.max(1,missingNames.length));missingNames.forEach((name,index)=>{const y=cardY+125+index*missingRowH;drawShareAvatar(ctx,portraits,{name,x:leftX+50,y,size:46,border:SHARE_BRAND.goldSoft,background:SHARE_BRAND.maroon});ctx.fillStyle=SHARE_BRAND.ink;const size=fitText(ctx,name,colW-125,29);ctx.font=`800 ${size}px Arial`;ctx.fillText(name,leftX+88,y+9);if(index<missingNames.length-1){ctx.strokeStyle="rgba(95,31,54,.09)";ctx.beginPath();ctx.moveTo(leftX+28,y+missingRowH/2);ctx.lineTo(leftX+colW-28,y+missingRowH/2);ctx.stroke()}});
 const submittedRowH=Math.min(115,640/Math.max(1,submittedPicks.length));submittedPicks.forEach((pick,index)=>{const y=cardY+118+index*submittedRowH;drawShareAvatar(ctx,portraits,{name:pick.name,x:rightX+48,y,size:44,border:"#84ad92",background:SHARE_BRAND.maroon});ctx.fillStyle=SHARE_BRAND.success;ctx.beginPath();ctx.arc(rightX+64,y+16,11,0,Math.PI*2);ctx.fill();ctx.fillStyle="white";ctx.font="900 12px Arial";ctx.textAlign="center";ctx.fillText("✓",rightX+64,y+20);ctx.textAlign="left";ctx.fillStyle=SHARE_BRAND.ink;const nameSize=fitText(ctx,pick.name,colW-116,25);ctx.font=`800 ${nameSize}px Arial`;ctx.fillText(pick.name,rightX+82,y-3);ctx.fillStyle=SHARE_BRAND.muted;const fixtureSize=fitText(ctx,pick.fixture,colW-118,17,13);ctx.font=`700 ${fixtureSize}px Arial`;ctx.fillText(pick.fixture,rightX+82,y+25);if(index<submittedPicks.length-1){ctx.strokeStyle="rgba(95,31,54,.08)";ctx.beginPath();ctx.moveTo(rightX+24,y+submittedRowH/2);ctx.lineTo(rightX+colW-24,y+submittedRowH/2);ctx.stroke()}});
 drawShareFooter(ctx,1080,1350);const blob=await canvasBlob(canvas);const file=new File([blob],`bounce-gw${gameweekNumber}-pick-reminder.png`,{type:"image/png"});const shareData:ShareData={title:`Bounce BTTS · GW${gameweekNumber} Pick Reminder`,text:`GW${gameweekNumber} pick reminder · ${missingNames.length} still to pick`,files:[file]};if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))await navigator.share(shareData);else{const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);window.alert("Reminder image created. Share the downloaded image to WhatsApp.")}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;window.alert(error instanceof Error?error.message:"Could not create reminder image.")}finally{setSharing(false)}}
 return <button type="button" className="dashboardGoldAction dashboardAdminAction" onClick={share} disabled={disabled||sharing||!missingNames.length} aria-label={missingNames.length?`Share reminder for ${missingNames.length} missing picks`:"All picks are in"}>{sharing?"Creating…":missingNames.length?"Remind Picks":"All Picks In ✓"}</button>;
}
