"use client";

import { useEffect,useMemo,useState } from "react";
import { createPortal } from "react-dom";
import DataShareButton from "./DataShareButton";

type Row={id:string;name:string;position:number;points:number;played:number;wins:number;scoreNil:number;zeroZero:number;strike:number;ppg:number;currentStreak:number;bestStreak:number;biggest:string;favourite:string;bestLeague:string;averageOdds:string;averageWinningOdds:string;positionChange:number;highestPosition:number;lowestPosition:number;weeksAtOne:number;gapToLeader:number;projection:number};
type StatsData={rows:Row[];headlines:{leader?:Row;bestForm?:Row;bestStrike?:Row;biggest?:Row;climber?:Row;mostWeeks?:Row};recap:string[];seasonLabel:string;gameweek:number};
function movement(value:number){return value>0?`↑ ${value}`:value<0?`↓ ${Math.abs(value)}`:"—"}
function ordinal(value:number){const n=value%100;if(n>=11&&n<=13)return`${value}th`;const x=value%10;return`${value}${x===1?"st":x===2?"nd":x===3?"rd":"th"}`}

export default function V2CompletionEnhancer(){
 const [hash,setHash]=useState("");const [gameweekId,setGameweekId]=useState("");const [target,setTarget]=useState<HTMLElement|null>(null);const [data,setData]=useState<StatsData|null>(null);
 useEffect(()=>{const read=()=>{setHash(window.location.hash);const select=document.querySelector('[aria-label="Choose gameweek"]') as HTMLSelectElement|null;setGameweekId(select?.value??"");const stats=document.querySelector('section[data-current-view="stats"] section') as HTMLElement|null;setTarget(stats)};read();window.addEventListener("hashchange",read);const timer=window.setInterval(read,500);return()=>{window.removeEventListener("hashchange",read);window.clearInterval(timer)}},[]);
 useEffect(()=>{if(!gameweekId||!(hash.includes("league-stats")||hash.includes("league-table")))return;let active=true;fetch(`/api/league-stats?gameweekId=${encodeURIComponent(gameweekId)}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(j=>{if(active&&j)setData(j)}).catch(()=>{});return()=>{active=false}},[gameweekId,hash]);
 useEffect(()=>{if(!target||!hash.includes("league-stats"))return;const originals=Array.from(target.children).filter(el=>!(el as HTMLElement).dataset.v2Completion);originals.slice(1).forEach(el=>{(el as HTMLElement).dataset.v2OldDisplay=(el as HTMLElement).style.display;(el as HTMLElement).style.display="none"});return()=>{originals.slice(1).forEach(el=>{const node=el as HTMLElement;node.style.display=node.dataset.v2OldDisplay??"";delete node.dataset.v2OldDisplay})}},[target,hash,data?.gameweek]);
 useEffect(()=>{document.querySelectorAll('[data-v2-movement]').forEach(n=>n.remove());if(!data||!hash.includes("league-table"))return;const table=document.querySelector('section[data-current-view="table"] section') as HTMLElement|null;if(!table)return;const byName=new Map(data.rows.map(r=>[r.name,r]));table.querySelectorAll('strong').forEach(strong=>{const row=byName.get(strong.textContent?.trim()??"");if(!row)return;const badge=document.createElement("span");badge.dataset.v2Movement="true";badge.className=`memberTableMove ${row.positionChange>0?"up":row.positionChange<0?"down":"flat"}`;badge.textContent=movement(row.positionChange);badge.title=`Movement since previous scored gameweek: ${movement(row.positionChange)}`;strong.appendChild(badge)});return()=>{document.querySelectorAll('[data-v2-movement]').forEach(n=>n.remove())}},[data,hash]);
 const shareRows=useMemo(()=>data?.rows.map(r=>[r.position,r.name,r.points,`${r.strike.toFixed(0)}%`,r.ppg.toFixed(1),movement(r.positionChange),r.biggest])??[],[data]);
 if(!target||!data||!hash.includes("league-stats"))return null;
 const h=data.headlines;
 return createPortal(<div className="memberStatsCompletion" data-v2-completion="true">
   <div className="memberStatsTopActions"><div><span>SEASON {data.seasonLabel} · THROUGH GW {data.gameweek}</span><strong>League intelligence</strong></div><DataShareButton title={`League Stats · GW ${data.gameweek}`} subtitle={`Season ${data.seasonLabel} · positions use official Bounce tie-break rules`} columns={["POS","PLAYER","PTS","SR%","PPG","MOVE","BIGGEST"]} rows={shareRows} fileName={`bounce-league-stats-gw${data.gameweek}.jpg`} label="Share league stats" compact/></div>
   <div className="memberStatsHeadlines"><article><span>LEAGUE LEADER</span><strong>{h.leader?.name??"—"}</strong><small>{h.leader?`${h.leader.points} pts`:"No scores"}</small></article><article><span>BEST FORM</span><strong>{h.bestForm?.currentStreak?h.bestForm.name:"—"}</strong><small>{h.bestForm?.currentStreak?`${h.bestForm.currentStreak} straight +3s`:"No active streak"}</small></article><article><span>HIGHEST STRIKE RATE</span><strong>{h.bestStrike?.name??"—"}</strong><small>{h.bestStrike?`${h.bestStrike.strike.toFixed(0)}%`:"—"}</small></article><article><span>BIGGEST WINNER</span><strong>{h.biggest?.biggest!=="—"?h.biggest?.name:"—"}</strong><small>{h.biggest?.biggest??"Waiting"}</small></article><article><span>BIGGEST CLIMBER</span><strong>{h.climber?.positionChange?h.climber.name:"—"}</strong><small>{h.climber?.positionChange?movement(h.climber.positionChange):"No climb yet"}</small></article><article><span>MOST WEEKS #1</span><strong>{h.mostWeeks?.weeksAtOne?h.mostWeeks.name:"—"}</strong><small>{h.mostWeeks?.weeksAtOne?`${h.mostWeeks.weeksAtOne} week${h.mostWeeks.weeksAtOne===1?"":"s"}`:"No history yet"}</small></article></div>
   <section className="memberStatsRecap"><div><span>GAMEWEEK RECAP</span><strong>What changed this week?</strong></div>{data.recap.map(line=><p key={line}>{line}</p>)}</section>
   <details className="memberStatsDetails"><summary><span>PLAYER COMPARISON</span><strong>Season performance</strong><small>Tap to expand</small></summary><div className="memberStatsTable"><div className="memberStatsRow head"><span>PLAYER</span><span>POS</span><span>MOVE</span><span>SR%</span><span>PPG</span><span>GAP</span><span>PROJ</span></div>{data.rows.map(r=><div className="memberStatsRow" key={r.id}><strong>{r.name}</strong><span>{r.position}</span><span className={r.positionChange>0?"moveUp":r.positionChange<0?"moveDown":""}>{movement(r.positionChange)}</span><span>{r.strike.toFixed(0)}%</span><span>{r.ppg.toFixed(1)}</span><span>{r.gapToLeader?`-${r.gapToLeader}`:"—"}</span><span>{r.projection}</span></div>)}</div><p className="statsProjectionNote">Projection is a simple current-points-per-scored-gameweek estimate across the scheduled season.</p></details>
   <details className="memberStatsDetails"><summary><span>PLAYER PROFILES</span><strong>Deep stats</strong><small>Tap to expand</small></summary><div className="memberPlayerGrid">{data.rows.map(r=><article key={r.id}><header><div><span>PLAYER PROFILE</span><h3>{r.name}</h3></div><strong>{r.points} pts · {ordinal(r.position)}</strong></header><div className="memberMetricGrid"><p><span>BTTS strike</span><b>{r.strike.toFixed(0)}%</b></p><p><span>Points / pick</span><b>{r.ppg.toFixed(1)}</b></p><p><span>Current streak</span><b>{r.currentStreak||"—"}</b></p><p><span>Best streak</span><b>{r.bestStreak||"—"}</b></p><p><span>Avg BTTS odds</span><b>{r.averageOdds}</b></p><p><span>Avg winning odds</span><b>{r.averageWinningOdds}</b></p><p><span>Biggest winner</span><b>{r.biggest}</b></p><p><span>Position change</span><b>{movement(r.positionChange)}</b></p><p><span>Highest position</span><b>{ordinal(r.highestPosition)}</b></p><p><span>Lowest position</span><b>{ordinal(r.lowestPosition)}</b></p><p><span>Weeks at #1</span><b>{r.weeksAtOne}</b></p><p><span>Gap to leader</span><b>{r.gapToLeader?`${r.gapToLeader} pts`:"Leader"}</b></p><p><span>Season projection</span><b>{r.projection} pts</b></p></div><footer><p><span>Most picked</span><strong>{r.favourite}</strong></p><p><span>Best league</span><strong>{r.bestLeague}</strong></p></footer></article>)}</div></details>
 </div>,target);
}
