export type HistoricalSeasonRow = {
  name: string;
  played: number;
  wins: number;
  scoreNil: number;
  losses: number;
  points: number;
};

export type HistoricalWeeklyRow = {
  name: string;
  weeklyResultCodes: number[];
  weeklyAwardedPoints: number[];
  awardTotal: number | null;
};

export type HistoricalSeason = {
  season: string;
  title: string;
  scoringNote: string;
  tablePointsNote: string;
  winner: string;
  runnerUp: string | null;
  weeks: number;
  finalTable: HistoricalSeasonRow[];
  weekly: HistoricalWeeklyRow[];
};

export const rollOfHonour = [
  {
    "season": "2024/25",
    "winner": "Dave S",
    "points": 20
  },
  {
    "season": "2025/26",
    "winner": "Ryan",
    "points": 29
  }
] as const;

export const historicalSeasons: HistoricalSeason[] = [
  {
    "season": "2024/25",
    "title": "Bounce BTTS League 2024/25",
    "scoringNote": "Historic season. Correct BTTS picks were worth 2 points in this era.",
    "tablePointsNote": "Final table points are preserved exactly as recorded in the source Numbers sheet.",
    "winner": "Dave S",
    "runnerUp": "Roy",
    "weeks": 32,
    "finalTable": [
      {
        "name": "Dave S",
        "played": 32,
        "wins": 22,
        "scoreNil": 8,
        "losses": 2,
        "points": 20
      },
      {
        "name": "Roy",
        "played": 32,
        "wins": 20,
        "scoreNil": 11,
        "losses": 1,
        "points": 19
      },
      {
        "name": "Pickup",
        "played": 32,
        "wins": 19,
        "scoreNil": 12,
        "losses": 1,
        "points": 18
      },
      {
        "name": "Ian",
        "played": 32,
        "wins": 17,
        "scoreNil": 14,
        "losses": 1,
        "points": 16
      },
      {
        "name": "Ryan",
        "played": 32,
        "wins": 17,
        "scoreNil": 13,
        "losses": 2,
        "points": 15
      },
      {
        "name": "Turnsy Fitchett",
        "played": 32,
        "wins": 18,
        "scoreNil": 10,
        "losses": 4,
        "points": 14
      },
      {
        "name": "DTB",
        "played": 32,
        "wins": 15,
        "scoreNil": 14,
        "losses": 3,
        "points": 12
      },
      {
        "name": "Dave P",
        "played": 32,
        "wins": 13,
        "scoreNil": 15,
        "losses": 4,
        "points": 9
      },
      {
        "name": "Yakky (oot)",
        "played": 32,
        "wins": 11,
        "scoreNil": 8,
        "losses": 13,
        "points": -2
      }
    ],
    "weekly": [
      {
        "name": "Dave S",
        "weeklyResultCodes": [
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          -1,
          1,
          1,
          1,
          -1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          0,
          1,
          1
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          2,
          -1,
          2,
          2,
          2,
          -1,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          2,
          1,
          1,
          2,
          2,
          1,
          2,
          2
        ],
        "awardTotal": 50
      },
      {
        "name": "Roy",
        "weeklyResultCodes": [
          0,
          1,
          1,
          1,
          0,
          1,
          -1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          0,
          1,
          0,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          1
        ],
        "weeklyAwardedPoints": [
          1,
          2,
          2,
          2,
          1,
          2,
          -1,
          1,
          2,
          2,
          2,
          2,
          2,
          1,
          1,
          2,
          2,
          1,
          2,
          1,
          1,
          2,
          1,
          2,
          2,
          2,
          2,
          2,
          1,
          1,
          2,
          2
        ],
        "awardTotal": 50
      },
      {
        "name": "Pickup",
        "weeklyResultCodes": [
          1,
          0,
          1,
          1,
          1,
          1,
          -1,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          0,
          1
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          2,
          2,
          2,
          2,
          -1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          2,
          1,
          1,
          1,
          2,
          2,
          2,
          2,
          2,
          2,
          1,
          1,
          2,
          2,
          2,
          1,
          2
        ],
        "awardTotal": 49
      },
      {
        "name": "Ian",
        "weeklyResultCodes": [
          1,
          0,
          -1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          -1,
          1,
          2,
          1,
          2,
          1,
          2,
          2,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          1,
          2,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          2,
          2,
          2,
          1
        ],
        "awardTotal": 47
      },
      {
        "name": "Ryan",
        "weeklyResultCodes": [
          1,
          0,
          0,
          0,
          1,
          1,
          0,
          -1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          -1,
          1,
          0,
          1,
          0,
          0,
          0
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          1,
          1,
          2,
          2,
          1,
          -1,
          2,
          2,
          1,
          2,
          2,
          2,
          2,
          2,
          1,
          1,
          2,
          2,
          2,
          2,
          1,
          2,
          1,
          -1,
          2,
          1,
          2,
          1,
          1,
          1
        ],
        "awardTotal": 45
      },
      {
        "name": "Turnsy Fitchett",
        "weeklyResultCodes": [
          1,
          1,
          1,
          1,
          -1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          -1,
          1,
          0,
          1,
          0,
          -1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          -1,
          1
        ],
        "weeklyAwardedPoints": [
          2,
          2,
          2,
          2,
          -1,
          2,
          2,
          2,
          1,
          2,
          2,
          2,
          1,
          1,
          2,
          2,
          -1,
          2,
          1,
          2,
          1,
          -1,
          2,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          -1,
          2
        ],
        "awardTotal": 42
      },
      {
        "name": "DTB",
        "weeklyResultCodes": [
          0,
          1,
          1,
          0,
          1,
          1,
          0,
          -1,
          0,
          -1,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          -1,
          0,
          1,
          1,
          0,
          1,
          1,
          1,
          1
        ],
        "weeklyAwardedPoints": [
          1,
          2,
          2,
          1,
          2,
          2,
          1,
          -1,
          1,
          -1,
          1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          2,
          1,
          1,
          1,
          2,
          -1,
          1,
          2,
          2,
          1,
          2,
          2,
          2,
          2
        ],
        "awardTotal": 41
      },
      {
        "name": "Dave P",
        "weeklyResultCodes": [
          -1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          -1,
          1,
          0,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          0,
          1,
          1,
          0,
          -1,
          1,
          0,
          -1,
          1,
          1
        ],
        "weeklyAwardedPoints": [
          -1,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          1,
          1,
          -1,
          2,
          1,
          1,
          2,
          2,
          2,
          1,
          2,
          1,
          1,
          2,
          2,
          1,
          -1,
          2,
          1,
          -1,
          2,
          2
        ],
        "awardTotal": 37
      },
      {
        "name": "Yakky (oot)",
        "weeklyResultCodes": [
          1,
          0,
          1,
          1,
          0,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          0,
          1,
          1,
          -1,
          -1,
          0,
          1,
          0,
          -1,
          -1,
          -1,
          -1,
          0,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          2,
          2,
          1,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          1,
          2,
          2,
          -1,
          -1,
          1,
          2,
          1,
          -1,
          -1,
          -1,
          -1,
          1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1
        ],
        "awardTotal": 17
      }
    ]
  },
  {
    "season": "2025/26",
    "title": "Bounce BTTS League 2025/26",
    "scoringNote": "Historic season. Correct BTTS picks were worth 2 points in this era.",
    "tablePointsNote": "Final table points are preserved exactly as recorded in the source Numbers sheet.",
    "winner": "Ryan",
    "runnerUp": "Dave S",
    "weeks": 38,
    "finalTable": [
      {
        "name": "Ryan",
        "played": 37,
        "wins": 29,
        "scoreNil": 8,
        "losses": 0,
        "points": 29
      },
      {
        "name": "Dave S",
        "played": 37,
        "wins": 26,
        "scoreNil": 11,
        "losses": 0,
        "points": 26
      },
      {
        "name": "Dave P",
        "played": 37,
        "wins": 23,
        "scoreNil": 13,
        "losses": 1,
        "points": 22
      },
      {
        "name": "Pickup",
        "played": 37,
        "wins": 21,
        "scoreNil": 14,
        "losses": 2,
        "points": 19
      },
      {
        "name": "Turnsy Fitchett",
        "played": 37,
        "wins": 20,
        "scoreNil": 15,
        "losses": 2,
        "points": 18
      },
      {
        "name": "Yacky",
        "played": 37,
        "wins": 21,
        "scoreNil": 12,
        "losses": 4,
        "points": 17
      },
      {
        "name": "DTB",
        "played": 37,
        "wins": 19,
        "scoreNil": 15,
        "losses": 3,
        "points": 16
      },
      {
        "name": "Shirley",
        "played": 37,
        "wins": 19,
        "scoreNil": 14,
        "losses": 4,
        "points": 15
      },
      {
        "name": "Ian",
        "played": 37,
        "wins": 16,
        "scoreNil": 17,
        "losses": 4,
        "points": 12
      }
    ],
    "weekly": [
      {
        "name": "Ryan",
        "weeklyResultCodes": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          0,
          1
        ],
        "weeklyAwardedPoints": [
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          1,
          2,
          2,
          2,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          1,
          1,
          2,
          2,
          2,
          1,
          2
        ],
        "awardTotal": 66
      },
      {
        "name": "Dave S",
        "weeklyResultCodes": [
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1
        ],
        "weeklyAwardedPoints": [
          1,
          2,
          1,
          2,
          2,
          2,
          2,
          1,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          2,
          2,
          2,
          2,
          1,
          1,
          2,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          2
        ],
        "awardTotal": 63
      },
      {
        "name": "Dave P",
        "weeklyResultCodes": [
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          0,
          -1
        ],
        "weeklyAwardedPoints": [
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          2,
          2,
          1,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          2,
          1,
          1,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          1,
          2,
          1,
          2,
          2,
          2,
          1,
          1,
          -1
        ],
        "awardTotal": 58
      },
      {
        "name": "Pickup",
        "weeklyResultCodes": [
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          0,
          -1,
          0,
          1,
          1,
          1,
          0,
          -1,
          1,
          1,
          1,
          0,
          1
        ],
        "weeklyAwardedPoints": [
          2,
          2,
          1,
          2,
          2,
          2,
          2,
          2,
          1,
          2,
          1,
          1,
          1,
          2,
          2,
          1,
          1,
          2,
          2,
          1,
          1,
          1,
          2,
          2,
          1,
          -1,
          1,
          2,
          2,
          2,
          1,
          -1,
          2,
          2,
          2,
          1,
          2
        ],
        "awardTotal": 54
      },
      {
        "name": "Turnsy Fitchett",
        "weeklyResultCodes": [
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          1,
          1,
          1,
          -1,
          0,
          1,
          0,
          -1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          0,
          1,
          0,
          0
        ],
        "weeklyAwardedPoints": [
          2,
          2,
          1,
          1,
          1,
          2,
          2,
          2,
          1,
          1,
          2,
          2,
          2,
          -1,
          1,
          2,
          1,
          -1,
          2,
          2,
          2,
          1,
          1,
          1,
          1,
          2,
          2,
          2,
          2,
          2,
          1,
          2,
          2,
          1,
          2,
          1,
          1
        ],
        "awardTotal": 53
      },
      {
        "name": "Yacky",
        "weeklyResultCodes": [
          1,
          0,
          1,
          1,
          0,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          1,
          1,
          0,
          1,
          -1,
          1,
          0,
          0,
          -1,
          1,
          1,
          0,
          -1,
          -1,
          0,
          0,
          1,
          1,
          1,
          0,
          1,
          0,
          1
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          2,
          2,
          1,
          2,
          2,
          1,
          2,
          2,
          2,
          2,
          2,
          1,
          2,
          2,
          1,
          2,
          -1,
          2,
          1,
          1,
          -1,
          2,
          2,
          1,
          -1,
          -1,
          1,
          1,
          2,
          2,
          2,
          1,
          2,
          1,
          2
        ],
        "awardTotal": 50
      },
      {
        "name": "DTB",
        "weeklyResultCodes": [
          1,
          0,
          0,
          1,
          -1,
          1,
          1,
          1,
          0,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          1,
          0,
          0,
          1,
          1,
          1,
          0,
          -1,
          0,
          1,
          1,
          1,
          1,
          0,
          1,
          0,
          1,
          0,
          -1,
          1,
          0
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          1,
          2,
          -1,
          2,
          2,
          2,
          1,
          1,
          2,
          1,
          2,
          1,
          2,
          1,
          2,
          1,
          1,
          2,
          2,
          2,
          1,
          -1,
          1,
          2,
          2,
          2,
          2,
          1,
          2,
          1,
          2,
          1,
          -1,
          2,
          1
        ],
        "awardTotal": 50
      },
      {
        "name": "Shirley",
        "weeklyResultCodes": [
          -1,
          1,
          1,
          1,
          0,
          1,
          0,
          0,
          1,
          0,
          1,
          1,
          1,
          0,
          1,
          1,
          1,
          1,
          -1,
          1,
          0,
          1,
          0,
          0,
          0,
          1,
          0,
          -1,
          1,
          -1,
          0,
          0,
          0,
          1,
          1,
          1,
          0
        ],
        "weeklyAwardedPoints": [
          -1,
          2,
          2,
          2,
          1,
          2,
          1,
          1,
          2,
          1,
          2,
          2,
          2,
          1,
          2,
          2,
          2,
          2,
          -1,
          2,
          1,
          2,
          1,
          1,
          1,
          2,
          1,
          -1,
          2,
          -1,
          1,
          1,
          1,
          2,
          2,
          2,
          1
        ],
        "awardTotal": 48
      },
      {
        "name": "Ian",
        "weeklyResultCodes": [
          1,
          0,
          1,
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          1,
          1,
          -1,
          -1,
          1,
          1,
          0,
          1,
          -1,
          1,
          1,
          -1,
          1,
          0,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0
        ],
        "weeklyAwardedPoints": [
          2,
          1,
          2,
          1,
          2,
          1,
          1,
          2,
          1,
          1,
          1,
          2,
          2,
          -1,
          -1,
          2,
          2,
          1,
          2,
          -1,
          2,
          2,
          -1,
          2,
          1,
          2,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          2,
          2,
          1,
          1
        ],
        "awardTotal": 45
      }
    ]
  }
];
