export type StatsProfile={id:string;name:string};
export type StatsGameweek={id:string;number:number};
export type StatsPrediction={gameweek_id:string;member_id:string;fixture_id:string;points_awarded:number|null};
export type StatsAdjustment={gameweek_id:string;member_id:string;points:number;reason:string};
export type StatsFixture={id:string;competition:string;country:string;odds_fractional:string|null};

export type LeagueStatRow={id:string;name:string;position:number;points:number;played:number;wins:number;scoreNil:number;zeroZero:number;strike:number;ppg:number;currentStreak:number;bestStreak:number;biggest:string;favourite:string;bestLeague:string;averageOdds:string;averageWinningOdds:string;positionChange:number;highestPosition:number;lowestPosition:number;weeksAtOne:number;gapToLeader:number;projection:number};

function normalise(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
export function competitionLabel(f:StatsFixture){const country=f.country.trim();const c=normalise(f.competition);if(country==="England"){if(c.includes("premier"))return"English Premier League";if(c.includes("championship"))return"English Championship";if(c.includes("league one"))return"English League One";if(c.includes("league two"))return"English League Two";}if(country==="Scotland"){if(c.includes("premiership"))return"Scottish Premiership";if(c.includes("championship"))return"Scottish Championship";if(c.includes("league one"))return"Scottish League One";if(c.includes("league two"))return"Scottish League Two";}return f.competition;}
export function fractionalDecimal(value:string|null){if(!value)return 0;const m=value.match(/(\d+)\s*\/\s*(\d+)/);return m?Number(m[1])/Math.max(1,Number(m[2])):0}
function decimalToFraction(value:number){if(!Number.isFinite(value)||value<=0)return"—";const denominators=[1,2,3,4,5,6,8,10,11,12,16,20];let best:[number,number]=[Math.round(value),1],error=Infinity;for(const d of denominators){const n=Math.max(1,Math.round(value*d));const e=Math.abs(n/d-value);if(e<error){best=[n,d];error=e}}return`${best[0]}/${best[1]}`}
function validAdjustment(a:StatsAdjustment,predictions:StatsPrediction[]){const scored=predictions.some(p=>p.member_id===a.member_id&&p.gameweek_id===a.gameweek_id&&p.points_awarded!=null);return !(scored&&a.reason.trim().toLowerCase()==="missed selection")}
function officialRows(profiles:StatsProfile[],weekIds:Set<string>,predictions:StatsPrediction[],adjustments:StatsAdjustment[]){return profiles.map(profile=>{let played=0,wins=0,scoreNil=0,zeroZero=0,points=0;for(const p of predictions){if(p.member_id!==profile.id||!weekIds.has(p.gameweek_id)||p.points_awarded==null)continue;played++;points+=p.points_awarded;if(p.points_awarded===3)wins++;else if(p.points_awarded===1)scoreNil++;else if(p.points_awarded===-1)zeroZero++;}for(const a of adjustments){if(a.member_id!==profile.id||!weekIds.has(a.gameweek_id)||!validAdjustment(a,predictions))continue;const scored=predictions.some(p=>p.member_id===a.member_id&&p.gameweek_id===a.gameweek_id&&p.points_awarded!=null);if(!scored)played++;points+=a.points;}return{id:profile.id,name:profile.name,played,wins,scoreNil,zeroZero,points}}).sort((a,b)=>b.points-a.points||a.zeroZero-b.zeroZero||b.wins-a.wins||a.name.localeCompare(b.name));}

export function computeLeagueStats(args:{profiles:StatsProfile[];gameweeks:StatsGameweek[];predictions:StatsPrediction[];adjustments:StatsAdjustment[];fixtures:StatsFixture[];cutoffNumber?:number}){
 const {profiles,predictions,adjustments,fixtures}=args;const ordered=[...args.gameweeks].sort((a,b)=>a.number-b.number);const cutoff=args.cutoffNumber??ordered.at(-1)?.number??0;const weeks=ordered.filter(g=>g.number<=cutoff);const ids=new Set(weeks.map(g=>g.id));const fixtureById=new Map(fixtures.map(f=>[f.id,f]));const weekById=new Map(ordered.map(g=>[g.id,g]));
 const standings=officialRows(profiles,ids,predictions,adjustments);const activeWeeks=weeks.filter(g=>predictions.some(p=>p.gameweek_id===g.id&&p.points_awarded!=null)||adjustments.some(a=>a.gameweek_id===g.id&&validAdjustment(a,predictions)));
 const timeline=activeWeeks.map((gw,index)=>{const included=new Set(activeWeeks.slice(0,index+1).map(g=>g.id));return{number:gw.number,rows:officialRows(profiles,included,predictions,adjustments).map((r,i)=>({...r,position:i+1}))}});
 const leaderPoints=standings[0]?.points??0;const totalPlanned=Math.max(ordered.length,cutoff);const completedWeeks=Math.max(1,activeWeeks.length);
 const rows:LeagueStatRow[]=standings.map((standing,standingIndex)=>{const profileId=standing.id;const picks=predictions.filter(p=>p.member_id===profileId&&ids.has(p.gameweek_id)).sort((a,b)=>(weekById.get(a.gameweek_id)?.number??999)-(weekById.get(b.gameweek_id)?.number??999));const scored=picks.filter(p=>p.points_awarded!=null);const wins=scored.filter(p=>p.points_awarded===3);let run=0,best=0;for(const p of scored){if(p.points_awarded===3){run++;best=Math.max(best,run)}else run=0}let current=0;for(let i=scored.length-1;i>=0;i--){if(scored[i].points_awarded===3)current++;else break}const priced=picks.map(p=>fixtureById.get(p.fixture_id)).filter((f):f is StatsFixture=>Boolean(f&&fractionalDecimal(f.odds_fractional)>0));const winFixtures=wins.map(p=>fixtureById.get(p.fixture_id)).filter((f):f is StatsFixture=>Boolean(f&&fractionalDecimal(f.odds_fractional)>0));const biggest=[...winFixtures].sort((a,b)=>fractionalDecimal(b.odds_fractional)-fractionalDecimal(a.odds_fractional))[0]?.odds_fractional??"—";const avg=priced.length?priced.reduce((s,f)=>s+fractionalDecimal(f.odds_fractional),0)/priced.length:0;const avgWins=winFixtures.length?winFixtures.reduce((s,f)=>s+fractionalDecimal(f.odds_fractional),0)/winFixtures.length:0;const comps=new Map<string,{p:number,w:number}>();for(const p of picks){const f=fixtureById.get(p.fixture_id);if(!f)continue;const k=competitionLabel(f);const x=comps.get(k)??{p:0,w:0};x.p++;if(p.points_awarded===3)x.w++;comps.set(k,x)}const favourite=[...comps.entries()].sort((a,b)=>b[1].p-a[1].p||a[0].localeCompare(b[0]))[0]?.[0]??"—";const bestLeague=[...comps.entries()].filter(([,v])=>v.p>0).sort((a,b)=>(b[1].w/b[1].p)-(a[1].w/a[1].p)||b[1].w-a[1].w||a[0].localeCompare(b[0]))[0]?.[0]??"—";const positions=timeline.map(t=>t.rows.find(r=>r.id===profileId)?.position).filter((p):p is number=>Boolean(p));const currentPosition=standingIndex+1;const previousPosition=timeline.length>1?(timeline.at(-2)?.rows.find(r=>r.id===profileId)?.position??currentPosition):currentPosition;return{id:profileId,name:standing.name,position:currentPosition,points:standing.points,played:standing.played,wins:standing.wins,scoreNil:standing.scoreNil,zeroZero:standing.zeroZero,strike:scored.length?wins.length/scored.length*100:0,ppg:standing.played?standing.points/standing.played:0,currentStreak:current,bestStreak:best,biggest,favourite,bestLeague,averageOdds:decimalToFraction(avg),averageWinningOdds:decimalToFraction(avgWins),positionChange:previousPosition-currentPosition,highestPosition:positions.length?Math.min(...positions):currentPosition,lowestPosition:positions.length?Math.max(...positions):currentPosition,weeksAtOne:positions.filter(p=>p===1).length,gapToLeader:Math.max(0,leaderPoints-standing.points),projection:Math.round((standing.points/completedWeeks)*totalPlanned)}});
 const bestForm=[...rows].sort((a,b)=>b.currentStreak-a.currentStreak||b.strike-a.strike)[0];const bestStrike=[...rows].filter(r=>r.played>0).sort((a,b)=>b.strike-a.strike||b.wins-a.wins)[0];const biggest=[...rows].sort((a,b)=>fractionalDecimal(b.biggest)-fractionalDecimal(a.biggest))[0];const climber=[...rows].sort((a,b)=>b.positionChange-a.positionChange||b.points-a.points)[0];const mostWeeks=[...rows].sort((a,b)=>b.weeksAtOne-a.weeksAtOne||a.position-b.position)[0];
 const currentWeek=activeWeeks.at(-1);const prev=timeline.at(-2);const now=timeline.at(-1);const changes=rows.map(r=>({name:r.name,move:r.positionChange,points:predictions.filter(p=>p.member_id===r.id&&p.gameweek_id===currentWeek?.id).reduce((s,p)=>s+(p.points_awarded??0),0)+adjustments.filter(a=>a.member_id===r.id&&a.gameweek_id===currentWeek?.id&&validAdjustment(a,predictions)).reduce((s,a)=>s+a.points,0)}));const biggestGain=[...changes].sort((a,b)=>b.points-a.points)[0];const biggestMove=[...changes].sort((a,b)=>b.move-a.move)[0];const oldLeader=prev?.rows[0]?.name;const newLeader=now?.rows[0]?.name;const recap=[oldLeader&&newLeader&&oldLeader!==newLeader?`${newLeader} took over at the top from ${oldLeader}.`:newLeader?`${newLeader} remains the league leader.`:"No leader yet.",biggestGain&&currentWeek?`${biggestGain.name} scored the most in GW ${currentWeek.number} (${biggestGain.points>=0?"+":""}${biggestGain.points}).`:"",biggestMove?.move>0?`${biggestMove.name} was the biggest climber, up ${biggestMove.move} place${biggestMove.move===1?"":"s"}.`:"No upward table movement this week."].filter(Boolean);
 return{rows,timeline,headlines:{leader:rows[0],bestForm,bestStrike,biggest,climber,mostWeeks},recap};
}
