import { createAdminClient } from "@/lib/supabase/admin";
import PublicLiveLeague from "./PublicLiveLeague";

export const dynamic="force-dynamic";
type Pred={id:string;gameweek_id:string;member_id:string;fixture_id:string;points_awarded:number|null};
type Fixture={id:string;gameweek_id:string|null;home_team:string;away_team:string;kickoff_at:string;status:string;home_score:number|null;away_score:number|null;odds_fractional:string|null;competition:string;country:string};
type Adjustment={gameweek_id:string;member_id:string;points:number;reason:string};
type PublicProfile={id:string;display_name:string};
type PublicGameweek={id:string;number:number;status:string;opens_at:string|null;locks_at:string};

export default async function PublicTablePage(){
 const admin=createAdminClient();const [{data:settings},{data:season},{data:profileData}]=await Promise.all([admin.from("league_settings").select("current_season_label,entry_fee").eq("id",true).maybeSingle(),admin.from("seasons").select("id,label").eq("is_current",true).maybeSingle(),admin.from("profiles").select("id,display_name").eq("approved",true).eq("active",true)]);const profiles=(profileData??[]) as PublicProfile[];const gwResponse=season?.id?await admin.from("gameweeks").select("id,number,status,opens_at,locks_at").eq("season_id",season.id).order("number"):null;const gameweeks=(gwResponse?.data??[]) as PublicGameweek[];const now=new Date().toISOString();const opened=gameweeks.filter(g=>!g.opens_at||g.opens_at<=now);const current=opened.find(g=>g.status==="open"&&g.locks_at>now)??opened[opened.length-1]??gameweeks[0]??null;const ids=gameweeks.map(g=>g.id);let predictions:Pred[]=[];let adjustments:Adjustment[]=[];if(ids.length){const [pr,ad]=await Promise.all([admin.from("predictions").select("id,gameweek_id,member_id,fixture_id,points_awarded").in("gameweek_id",ids),admin.from("score_adjustments").select("gameweek_id,member_id,points,reason").in("gameweek_id",ids)]);predictions=(pr.data??[]) as Pred[];adjustments=(ad.data??[]) as Adjustment[];}const fixtureIds=[...new Set(predictions.map(p=>p.fixture_id))];let fixtures:Fixture[]=[];if(fixtureIds.length){const fx=await admin.from("fixtures").select("id,gameweek_id,home_team,away_team,kickoff_at,status,home_score,away_score,odds_fractional,competition,country").in("id",fixtureIds);fixtures=(fx.data??[]) as Fixture[];}return <PublicLiveLeague seasonLabel={season?.label??settings?.current_season_label??"2026/27"} entryFee={Number(settings?.entry_fee??20)} gameweeks={gameweeks} profiles={profiles} predictions={predictions} adjustments={adjustments} fixtures={fixtures} initialGameweekId={current?.id??gameweeks[0]?.id??""}/>;
}
