"use client";

import { useEffect,useMemo,useState } from "react";
import { computeLeagueStats } from "@/lib/league-stats";

type Gameweek={id:string;number:number;status:string;opens_at:string|null;locks_at:string};
type Profile={id:string;display_name:string};
type Pred={id:string;gameweek_id:string;member_id:string;fixture_id:string;points_awarded:number|null};
type Adjustment={gameweek_id:string;member_id:string;points:number;reason:string};
type Fixture={id:string;gameweek_id:string|null;home_team:string;away_team:string;kickoff_at:string;status:string;home_score:number|null;away_score:number|null;odds_fractional:string|null;competition:string;country:string};
type LiveFixture={id:string;status:string;elapsed:number|null;homeScore:number|null;awayScore:number|null};
const liveStatuses=new Set(["1H","HT","2H","ET","P","BT","INT"]);const finished=new Set(["FT","AET","PEN"]);
function competition(f:Fixture){const c=f.competition.toLowerCase();if(f.country==="England"&&c.includes("premier"))return"English Premier League";if(f.country==="England"&&c.includes("championship"))return"English Championship";if(f.country==="England"&&c.includes("league one"))return"English League One";if(f.country==="England"&&c.includes("league two"))return"English League Two";return f.competition;}
function outcome(f:Fixture,p:Pred):[string,string]{if(p.points_awarded===3)return["BTTS WON +3","good"];if(p.points_awarded===1)return["SCORE-NIL +1","warn"];if(p.points_awarded===-1)return["0-0 -1","bad"];if(f.home_score!=null&&f.away_score!=null){if(f.home_score>0&&f.away_score>0)return[finished.has(f.status)?"BTTS WON +3":"BTTS WINNING","good"];if(f.home_score===0&&f.away_score===0)return[finished.has(f.status)?"0-0 -1":"0-0 LIVE","bad"];return[finished.has(f.status)?"SCORE-NIL +1":"SCORE-NIL LIVE","warn"]}return["PENDING","neutral"]}
function statusText(f:Fixture){if(liveStatuses.has(f.status)&&typeof (f as Fixture&{live_elapsed?:number|null}).live_elapsed==="number")return`${(f as Fixture&{live_elapsed?:number|null}).live_elapsed}′`;return f.status;}
function move(v:number){return v>0?`↑${v}`:v<0?`↓${Math.abs(v)}`:"—"}

export default function PublicLiveLeague({seasonLabel,entryFee,gameweeks,profiles,predictions,adjustments,fixtures,initialGameweekId}:{seasonLabel:string;entryFee:number;gameweeks:Gameweek[];profiles:Profile[];predictions:Pred[];adjustments:Adjustment[];fixtures:Fixture[];initialGameweekId:string}){
 const [gameweekId,setGameweekId]=useState(initialGameweekId);const [live,setLive]=useState<Record<string,LiveFixture>>({});
 const gameweek=gameweeks.find(g=>g.id===gameweekId)??gameweeks[0];
 const shownFixtures=useMemo(()=>fixtures.map(f=>{const x=live[f.id];return x?{...f,status:x.status,home_score:x.homeScore??f.home_score,away_score:x.awayScore??f.away_score,live_elapsed:x.elapsed}:f}),[fixtures,live]);
 const stats=useMemo(()=>computeLeagueStats({profiles:profiles.map(p=>({id:p.id,name:p.display_name})),gameweeks,predictions,adjustments,fixtures,cutoffNumber:gameweek?.number??0}),[profiles,gameweeks,predictions,adjustments,fixtures,gameweek?.number]);
 const currentPreds=predictions.filter(p=>p.gameweek_id===gameweek?.id);const picks=profiles.map(profile=>{const p=currentPreds.find(x=>x.member_id===profile.id);const f=shownFixtures.find(x=>x.id===p?.fixture_id);return{profile,p,f}});const liveCount=picks.filter(x=>x.f&&liveStatuses.has(x.f.status)).length;
 useEffect(()=>{let cancelled=false;async function poll(){if(!gameweek?.id)return;try{const r=await fetch(`/api/public-live-results?gameweekId=${encodeURIComponent(gameweek.id)}`,{cache:"no-store"});if(!r.ok)return;const j=await r.json();if(!cancelled&&Array.isArray(j.fixtures))setLive(Object.fromEntries((j.fixtures as LiveFixture[]).map(x=>[x.id,x])))}catch{}}void poll();const timer=window.setInterval(poll,15000);return()=>{cancelled=true;window.clearInterval(timer)}},[gameweek?.id]);
 return <main className="spectatorPage"><header className="spectatorHero"><div className="spectatorHeroCopy"><span>PRIVATE SPECTATOR VIEW · SEASON {seasonLabel}</span><h1>BOUNCE</h1><h2>BTTS LEAGUE</h2><p>Current and historical picks, near-live scores and the league race — read only.</p></div></header><nav className="spectatorNav"><a className="active" href="/table">Live League</a><a href="/stats">League Stats</a><a href="/login">Member Login</a></nav>
 <div className="publicGwBrowser"><button disabled={gameweeks.findIndex(g=>g.id===gameweekId)<=0} onClick={()=>{const i=gameweeks.findIndex(g=>g.id===gameweekId);if(i>0)setGameweekId(gameweeks[i-1].id)}}>‹</button><label><span>HISTORICAL SNAPSHOT</span><select value={gameweekId} onChange={e=>setGameweekId(e.target.value)}>{gameweeks.map(g=><option key={g.id} value={g.id}>GW {g.number}</option>)}</select></label><button disabled={gameweeks.findIndex(g=>g.id===gameweekId)>=gameweeks.length-1} onClick={()=>{const i=gameweeks.findIndex(g=>g.id===gameweekId);if(i>=0&&i<gameweeks.length-1)setGameweekId(gameweeks[i+1].id)}}>›</button></div>
 <section className="spectatorStatus"><article><span>GAMEWEEK</span><strong>GW {gameweek?.number??"—"}</strong><small>{gameweek?.status?.toUpperCase()??"—"}</small></article><article><span>LIVE NOW</span><strong>{liveCount}</strong><small>selected matches</small></article><article><span>LEADER AT GW {gameweek?.number??"—"}</span><strong>{stats.rows[0]?.name??"—"}</strong><small>{stats.rows[0]?`${stats.rows[0].points} pts`:"No scores"}</small></article><article><span>SEASON POT</span><strong>£{(profiles.length*entryFee).toFixed(0)}</strong><small>{profiles.length} players</small></article></section>
 <section className="spectatorSection"><div className="spectatorHeading"><div><span>GAMEWEEK {gameweek?.number??"—"}</span><h3>Everyone&apos;s picks</h3><p>{gameweek?.id===initialGameweekId?"Near-live scores refresh automatically.":"Historical scores and outcomes for this gameweek."}</p></div><b>{currentPreds.length}/{profiles.length} picks</b></div><div className="spectatorPicks">{picks.map(({profile,p,f})=>{const state:[string,string]=f&&p?outcome(f,p):["AWAITING PICK","neutral"];return <article key={profile.id} className={`spectatorPick ${state[1]}`}><div className="spectatorPlayer"><span>{profile.display_name.split(/\s+/).map(part=>part[0]).join("").slice(0,2)}</span><strong>{profile.display_name}</strong></div>{f?<><div className="spectatorFixture"><strong>{f.home_team} <em>v</em> {f.away_team}</strong><small>{competition(f)} · BTTS {f.odds_fractional??"—"}</small></div><div className="spectatorScore"><strong>{f.home_score==null?"—":`${f.home_score}-${f.away_score}`}</strong><small>{statusText(f)}</small></div></>:<div className="spectatorFixture"><strong>Awaiting selection</strong><small>Nothing submitted</small></div>}<div className="spectatorOutcome">{state[0]}</div></article>})}</div></section>
 <section className="spectatorSection"><div className="spectatorHeading"><div><span>STANDINGS AFTER GW {gameweek?.number??"—"}</span><h3>League Table</h3><p>This is the cumulative table exactly through the selected gameweek.</p></div><a href="/stats">Explore League Stats →</a></div><div className="spectatorTable"><div className="spectatorTableRow head publicMovement"><span>POS</span><span>PLAYER</span><span>MOVE</span><span>P</span><span>W</span><span>0-0</span><span>PTS</span></div>{stats.rows.map((r,i)=><div className={`spectatorTableRow publicMovement ${i===0?"leader":""}`} key={r.id}><span>{i===0?"🏆":i+1}</span><strong>{r.name}</strong><span className={r.positionChange>0?"moveUp":r.positionChange<0?"moveDown":""}>{move(r.positionChange)}</span><span>{r.played}</span><span>{r.wins}</span><span>{r.zeroZero}</span><b>{r.points}</b></div>)}</div><p className="spectatorRule">Ties: fewest 0–0 results, most BTTS wins, then alphabetical.</p></section><footer className="spectatorFooter"><div><strong>BOUNCE BTTS LEAGUE</strong><span>Edinburgh · Est 2024</span></div></footer></main>;
}
