create table if not exists public.easter_egg_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists easter_egg_events_user_event_idx
  on public.easter_egg_events (user_id, event_key);

alter table public.easter_egg_events enable row level security;
